### ISSUE TITLE
Unminified source code in build?

### ISSUE THREAD

**Issue by simpleshadow** [mars/create-react-app-buildpack#100]
Using create-react-app-buildpack with Dokku. Can't quite figure out why [I'm able to see my source code](https://cl.ly/2Y0l0Q1q1E2j) once built and deployed with the buildlpack. It appears the react app is using, in `index.html`, the minified version at `/static/js` (where my source code is seen). Seems strange there's another directory `/static/static/js` (with the minified source) and `/static/node_modules` as well.

Strangely enough, when I enter the app in Dokku, `/build` does not have the source code so I have no idea how it's getting there.  

Any ideas what's going on?

**Comment by mars** [comment]
This buildpack deploys what [**facebook/create-react-app**](https://github.com/facebook/create-react-app) produces with its build command, `react-scripts build`.

If you think you found a bug or want to propose a change in the javascript build & bundle process, please do so on that repo.

That said, I think what you’re seeing in your browser is the dev tools rendering the complete module tree from the source maps. After all, the browser does receive a complete bundle of the code, so modern browsers make it as easy as possible to analyze & debug javascript apps!

**Comment by prem2282** [comment]
so how do i make sure source code is not visible to the world?

**Comment by simpleshadow** [comment]
> so how do i make sure source code is not visible to the world?

@prem2282 Add the following to your `.env`:
```
GENERATE_SOURCEMAP=false
```

**Comment by prem2282** [comment]
> > so how do i make sure source code is not visible to the world?
> 
> @prem2282 Add the following to your `.env`:
> 
> ```
> GENERATE_SOURCEMAP=false
> ```

thank you @simpleshadow but sorry if I sound dumb, i dont know where to find the .env file. could you please let me know where can i locate it

**Comment by simpleshadow** [comment]
@prem2282 [Adding Development Environment Variables In `.env`](https://facebook.github.io/create-react-app/docs/adding-custom-environment-variables#adding-development-environment-variables-in-env)

**Comment by mars** [comment]
Even if the source maps are skipped, not present, all of the JavaScript is still sent to the browser for interpretation & execution, **visible to anyone who can fetch the React app.**

Do not fool yourself into believing you can hide web page source. You can obfuscate the source code, but inevitably it always has to be decoded in the browser, accessible through browsers’ built-in dev tools.

The exception to this is DRM (for commercial video streaming) built into browsers to prevent the end user from decoding the received data.
