### ISSUE TITLE
Cannot deploy production build

### ISSUE THREAD

**Issue by Kashkovsky** [mars/create-react-app-buildpack#105]
Hi, I'm trying to deploy production build of CRA on heroku.
Here's my static.json:
```
{
  "root": "build/",
  "routes": {
    "/**": "index.html"
  }
}
```
Procfile:
```
web: bin/boot
```
However the app is served in dev mode, logs:
```
Counting objects: 1, done.
Writing objects: 100% (1/1), 189 bytes | 189.00 KiB/s, done.
Total 1 (delta 0), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> React.js (create-react-app) multi app detected
remote: -----> Configure create-react-app build environment
remote:        Using `NODE_ENV=development`
remote: =====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-multi.git
remote: =====> Detected Framework: Multipack
remote: =====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-nodejs.git
remote: =====> Detected Framework: Node.js
remote:
remote: -----> Creating runtime environment
remote:
remote:        NPM_CONFIG_LOGLEVEL=error
remote:        NPM_CONFIG_PRODUCTION=true
remote:        NODE_VERBOSE=false
remote:        NODE_ENV=production
remote:        NODE_MODULES_CACHE=true
remote:
remote: -----> Installing binaries
remote:        engines.node (package.json):  unspecified
remote:        engines.npm (package.json):   unspecified (use default)
remote:
remote:        Resolving node version 8.x...
remote:        Downloading and installing node 8.11.2...
remote:        Using default npm version: 5.6.0
remote:
remote: -----> Restoring cache
remote:        Loading 2 from cacheDirectories (default):
remote:        - node_modules
remote:        - bower_components (not cached - skipping)
remote:
remote: -----> Building dependencies
remote:        Installing node modules (package.json + package-lock)
remote:        up to date in 11.807s
remote:
remote: -----> Caching build
remote:        Clearing previous node cache
remote:        Saving 2 cacheDirectories (default):
remote:        - node_modules
remote:        - bower_components (nothing to cache)
remote:
remote: -----> Pruning devDependencies
remote:        Skipping because NPM_CONFIG_PRODUCTION is 'true'
remote:
remote: -----> Build succeeded!
remote: =====> Downloading Buildpack: https://github.com/mars/create-react-app-inner-buildpack.git
remote: =====> Detected Framework: React.js (create-react-app)
remote:        Using existing `static.json`
remote:        Enabling runtime environment variables
remote:
remote: > stitch@0.1.0 build /tmp/build_29d8ea3bfc23f7a536c5ffe6f928d31f
remote: > npm-run-all build-css build-js
remote:
remote:
remote: > stitch@0.1.0 build-css /tmp/build_29d8ea3bfc23f7a536c5ffe6f928d31f
remote: > node-sass-chokidar src/ -o src/
remote:
remote: Wrote 7 CSS files to /tmp/build_29d8ea3bfc23f7a536c5ffe6f928d31f/src/
remote:
remote: > stitch@0.1.0 build-js /tmp/build_29d8ea3bfc23f7a536c5ffe6f928d31f
remote: > node scripts/build.js
remote:
remote: Creating an optimized production build...
remote: Compiled successfully.
remote:
remote: File sizes after gzip:
remote:
remote:   502.99 KB  build/static/js/main.572e63f6.js
remote:   40.03 KB   build/static/css/main.1c010e02.css
remote:
remote: The project was built assuming it is hosted at the server root.
remote: You can control this with the homepage field in your package.json.
remote: For example, add this to build it for GitHub Pages:
remote:
remote:   "homepage" : "http://myname.github.io/myapp",
remote:
remote: The build folder is ready to be deployed.
remote: You may serve it with a static server:
remote:
remote:   npm install -g serve
remote:   serve -s build
remote:
remote: Find out more about deployment here:
remote:
remote:   http://bit.ly/2vY88Kr
remote:
remote: =====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-static.git
remote: =====> Detected Framework: Static HTML
remote:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
remote:                                  Dload  Upload   Total   Spent    Left  Speed
remote: 100  838k  100  838k    0     0  4198k      0 --:--:-- --:--:-- --:--:-- 4214k
remote: -----> Installed directory to /app/bin
remote: Using release configuration from last framework (Static HTML).
remote: -----> Discovering process types
remote:        Procfile declares types -> web
remote:
remote: -----> Compressing...
remote:        Done: 63.2M
remote: -----> Launching...
remote:        Released v36
remote:        https://stitch-dev.herokuapp.com/ deployed to Heroku
remote:
remote: Verifying deploy... done.
To https://git.heroku.com/stitch-dev.git
   3a68abc..e058cca  master -> master
```
Note that ```Configure create-react-app build environment Using `NODE_ENV=development` ```
How can i publish production build served from /build folder?

**Comment by mars** [comment]
Hi @Kashkovsky ,

This buildpack does produce the production build. Look further down in the logs and you’ll see:

```
Creating an optimized production build...
```

 That `NODE_ENV` setting is purely to get the devDependencies installed. No matter what `NODE_ENV` is set to, create-react-app’s build command always produces production build.

**Comment by JustinTime42** [comment]
I'm having a similar issue here. It says that it is creating an optimized production build, but when I look at the site and open up the React Developer Tools plugin, it says that it is using a development build.

**Comment by mars** [comment]
@JustinTime42 I just tried a fresh, default deployment (without any config changes), and it still deploys a production build:

![screen shot 2018-07-10 at 14 45 41](https://user-images.githubusercontent.com/17164/42539452-0259b332-8450-11e8-8707-657c9354d78d.png)

**Comment by mars** [comment]
@JustinTime42 I just checked your app, and it is using the production build:

![screen shot 2018-07-10 at 14 53 06](https://user-images.githubusercontent.com/17164/42539776-043e7ba0-8451-11e8-954d-8a5fd23034ad.png)

**Comment by JustinTime42** [comment]
Thanks for looking into that. However, that's not my app. I've built this site: http://www.filmyourwayproductions.com/
It is built with create-react-app and deployed to heroku with create-react-app-buildpack.

**Comment by mars** [comment]
@JustinTime42 sorry for the confusion. As I verified, this buildpack does still produce a production build by default, so something has been modified in your app. We would definitely need more info to help you debug:

What buildpack is set on your app? Check with `heroku buildpacks`.

Did you set any config vars? Check with `heroku config`.

Has the build command been modified? Check `package.json` `"scripts"` section.

Has this app been ejected from create-react-app?

Feel free to paste these results here, so I can help you debug.

**Comment by mars** [comment]
Also, is there a custom `Procfile` defined? What does it contain?

**Comment by JustinTime42** [comment]
Buildpacks: 
=== film-your-way-site Buildpack URLs
1. https://github.com/mars/create-react-app-buildpack.git
2. heroku/nodejs

heroku config
=== film-your-way-site Config Vars
NODE_ENV:              production

Package.json scripts: 
"scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject",
    "predeploy": "npm run build",
    "deploy": "gh-pages -d build"
  },

App has not been ejected from create-react-app

**Comment by JustinTime42** [comment]
Also no custom procfile

**Comment by mars** [comment]
@JustinTime42 When `heroku/nodejs` is set as the last buildpack, the app launches with `npm start` which runs the create-react-app dev server.

Set the app to use only this buildpack, redeploy, and it will serve production build:

```bash
heroku buildpacks:set https://github.com/mars/create-react-app-buildpack.git
git commit --allow-empty -m 'Deploy with only create-react-app-buildpack'
git push heroku master
```

This buildpack already includes Node for the production build process, but it launches an Nginx static web server for production. See: [Architecture](https://github.com/mars/create-react-app-buildpack#user-content-architecture-)

**Comment by JustinTime42** [comment]
gosh yeah that fixed it. I should have read that section of the docs more closely! Thanks for your help!
