### ISSUE TITLE
Not serving public files

### ISSUE THREAD

**Issue by vincentleeuwen** [mars/create-react-app-buildpack#108]
Hi there, 

I'm having difficulties to get the files in my public folder showing in production. I suspect it has to do with my routes settings ` "/**": "index.html"`, pointing all urls to a client side router. I would like to have my favicons and manifest.json loaded from public folder though.

**static.json:**

```
{
  "root": "build/",
  "https_only": true,
  "headers": {
    "/**": {
      "Strict-Transport-Security": "max-age=7776000"
    }
  },
  "clean_urls": false,
  "routes": {
    "/favicon/*": "/favicon/",
    "/**": "index.html"
  }
}
```

**Folder structure:**

```
|-- public
   |-- index.html
   |-- favicon
      |-- favicon.ico
      |-- manifest.json
      |-- // etc.
```

I can't really wrap my head around how I should link up my public folder as well as keeping my client side routing working? Any help much appreciated!

**Comment by mars** [comment]
`public/` is the place to put static files. That’s [a feature of create-react-app](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#using-the-public-folder). No special routing necessary.

Did you `git add public/` & commit them to git?

**Comment by evancorl** [comment]
@vincentleeuwen This is happening to me too. I've noticed that my file (a Word document) works for http but not https.
