### ISSUE TITLE
Cannot proxy requests to my API

### ISSUE THREAD

**Issue by DNonov** [mars/create-react-app-buildpack#111]
Hi,
I've created create-react-app-buildpack app at https://warbler-client-app.herokuapp.com.
I've got API at https://warbler-server-app.herokuapp.com.
So I want to proxy all requests and I have the following static.json
``` JSON
{
	"root": "build/",
	"routes": {
		"/**": "index.html"
	},
	"proxies": {
		"/api": {
			"origin": "https://warbler-server-app.herokuapp.com" 
		}
	}
}
```

and instead  of having requests at https://warbler-server-app.herokuapp.com/api
I've got https://warbler-client-app.herokuapp.com/api

here is the build:
Counting objects: 3, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 288 bytes | 0 bytes/s, done.
Total 3 (delta 2), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> React.js (create-react-app) multi app detected
remote: -----> Configure create-react-app build environment
remote:        Using `NODE_ENV=development`
remote: =====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-multi.git
remote: =====> Detected Framework: Multipack
remote: =====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-nodejs.git
remote: =====> Detected Framework: Node.js
remote:
remote: -----> Creating runtime environment
remote:
remote:        NPM_CONFIG_LOGLEVEL=error
remote:        NPM_CONFIG_PRODUCTION=false
remote:        NODE_VERBOSE=false
remote:        NODE_ENV=development
remote:        NODE_MODULES_CACHE=true
remote:
remote: -----> Installing binaries
remote:        engines.node (package.json):  unspecified
remote:        engines.npm (package.json):   unspecified (use default)
remote:
remote:        Resolving node version 8.x...
remote:        Downloading and installing node 8.11.3...
remote:        Using default npm version: 5.6.0
remote:
remote: -----> Restoring cache
remote:        Loading 2 from cacheDirectories (default):
remote:        - node_modules
remote:        - bower_components (not cached - skipping)
remote:
remote: -----> Building dependencies
remote:        Installing node modules (package.json + package-lock)
remote:        up to date in 11.123s
remote:
remote: -----> Caching build
remote:        Clearing previous node cache
remote:        Saving 2 cacheDirectories (default):
remote:        - node_modules
remote:        - bower_components (nothing to cache)
remote:
remote: -----> Pruning devDependencies
remote:        Skipping because NODE_ENV is not 'production'
remote:
remote: -----> Build succeeded!
remote: =====> Downloading Buildpack: https://github.com/mars/create-react-app-inner-buildpack.git
remote: =====> Detected Framework: React.js (create-react-app)
remote:        Using existing `static.json`
remote:        Enabling runtime environment variables
remote:
remote: > client@0.1.0 build /tmp/build_1e13614a3ed8777791e0e4aeddf51b45
remote: > react-scripts build
remote:
remote: Creating an optimized production build...
remote: Compiled with warnings.
remote:
remote: ./src/containers/App.js
remote:   Line 1:  'Component' is defined but never used  no-unused-vars
remote:
remote: ./src/containers/Main.js
remote:   Line 2:  'Redirect' is defined but never used  no-unused-vars
remote:
remote: Search for the keywords to learn more about each warning.
remote: To ignore, add // eslint-disable-next-line to the line before.
remote:
remote: File sizes after gzip:
remote:
remote:   88.54 KB  build/static/js/main.c4fa9cbb.js
remote:   1.28 KB   build/static/css/main.41dfe39d.css
remote:
remote: The project was built assuming it is hosted at the server root.
remote: You can control this with the homepage field in your package.json.
remote: For example, add this to build it for GitHub Pages:
remote:
remote:   "homepage" : "http://myname.github.io/myapp",
remote:
remote: The build folder is ready to be deployed.
remote: You may serve it with a static server:
remote:
remote:   npm install -g serve
remote:   serve -s build
remote:
remote: Find out more about deployment here:
remote:
remote:   http://bit.ly/2vY88Kr
remote:
remote: =====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-static.git
remote: =====> Detected Framework: Static HTML
remote:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
remote:                                  Dload  Upload   Total   Spent    Left  Speed
remote: 100  838k  100  838k    0     0  5941k      0 --:--:-- --:--:-- --:--:-- 5947k
remote: -----> Installed directory to /app/bin
remote: Using release configuration from last framework (Static HTML).
remote: -----> Discovering process types
remote:        Procfile declares types     -> (none)
remote:        Default types for buildpack -> web
remote:
remote: -----> Compressing...
remote:        Done: 52.5M
remote: -----> Launching...
remote:        Released v22
remote:        https://warbler-client-app.herokuapp.com/ deployed to Heroku
remote:
remote: Verifying deploy... done.
To https://git.heroku.com/warbler-client-app.git
   eb4b041..1c08b9b  master -> master

**Comment by mars** [comment]
Hi @DNonov ,

It's not apparent why your [Proxy for deployment](https://github.com/mars/create-react-app-buildpack/blob/master/README.md#user-content-proxy-for-deployment) config would not be working.

Did you commit the `static.json` changes to git, and then redeploy `git push heroku master`? Are you working on a branch? Because then deployment would require specifying the local branch, e.g. `git push heroku local-branch:master`.

Maybe the missing trailing slash in your `"proxies"`: `"/api"` property name would cause this problem? The docs show that it should be `"/api/"`.

Did you update the calling code in your client app to use the self-referential `https://warbler-client-app.herokuapp.com/api/` or relative `/api/` paths? If the requests are going to the wrong hostname, then my guess is that the app is not actually making requests to the proxy.
