### ISSUE TITLE
My reactjs weblink not opening in incognito mode and mobile browser

### ISSUE THREAD

**Issue by princecharmx** [mars/create-react-app-buildpack#113]
https://invock-web-client-prod.herokuapp.com/view/shared-voucher/5b63e7047dba920014c9e79f

This link opens in normal browser. But fails to load in incognito mode/mobile browser.

@mars please advise

**Comment by mars** [comment]
Hi @princecharmx,

Sorry to hear you’re having trouble making your links work. I’m unaware of anything that would make a site open links differently in differently browsers, outside of the ever-present, everchanging differences between web browsers!

To diagnose, try opening the developer/debug console in those browsers and then follow the link. The dev console will reveal errors or at least give you some insight into how the page is rendering.

If you encounter issues with this buildpack’s deployment process, I’m happy to help, but these issues are not for general web development questions.
