### ISSUE TITLE
Add basic auth

### ISSUE THREAD

**Issue by ollieglass** [mars/create-react-app-buildpack#114]
Would it be possible to add basic auth to this buildpack please? That would be very useful.

**Comment by mars** [comment]
You can use a fork like [Substantial's](https://github.com/substantial/create-react-app-buildpack) (based on [this PR](https://github.com/heroku/heroku-buildpack-static/pull/45)), until this someday magically happens ✨

**Comment by mars** [comment]
A new fork of this buildpack, [crak-buildpack](https://github.com/mars/crak-buildpack), is now available that serves the React app using a Kong gateway.

[Kong plugins](https://docs.konghq.com/hub/) may be used to implement authentication and more.

Please try it out & file issues (feedback or bugs) on the [crak-buildpack](https://github.com/mars/crak-buildpack).
