### ISSUE TITLE
Nginx Configuration

### ISSUE THREAD

**Issue by luskin** [mars/create-react-app-buildpack#119]
We are interested in using [Prerender](prerender.io) but in order to do so we must add some `nginx` configuration as so:

```
# Change YOUR_TOKEN to your prerender token and uncomment that line if you want to cache urls and view crawl stats
# Change example.com (server_name) to your website url
# Change /path/to/your/root to the correct value

server {
    listen 80;
    server_name example.com;
 
    root   /path/to/your/root;
    index  index.html;

    location / {
        try_files $uri @prerender;
    }
 
    location @prerender {
        #proxy_set_header X-Prerender-Token YOUR_TOKEN;
        
        set $prerender 0;
        if ($http_user_agent ~* "googlebot|bingbot|yandex|baiduspider|twitterbot|facebookexternalhit|rogerbot|linkedinbot|embedly|quora link preview|showyoubot|outbrain|pinterest|slackbot|vkShare|W3C_Validator") {
            set $prerender 1;
        }
        if ($args ~ "_escaped_fragment_") {
            set $prerender 1;
        }
        if ($http_user_agent ~ "Prerender") {
            set $prerender 0;
        }
        if ($uri ~* "\.(js|css|xml|less|png|jpg|jpeg|gif|pdf|doc|txt|ico|rss|zip|mp3|rar|exe|wmv|doc|avi|ppt|mpg|mpeg|tif|wav|mov|psd|ai|xls|mp4|m4a|swf|dat|dmg|iso|flv|m4v|torrent|ttf|woff|svg|eot)") {
            set $prerender 0;
        }
        
        #resolve using Google's DNS server to force DNS resolution and prevent caching of IPs
        resolver 8.8.8.8;
 
        if ($prerender = 1) {
            
            #setting prerender as a variable forces DNS resolution since nginx caches IPs and doesnt play well with load balancing
            set $prerender "service.prerender.io";
            rewrite .* /$scheme://$host$request_uri? break;
            proxy_pass http://$prerender;
        }
        if ($prerender = 0) {
            rewrite .* /index.html break;
        }
    }
}
```

Without having to fork this repo, is there any way we can accommodate this?

**Comment by mars** [comment]
Hi @luskin 😃

No, this buildpack does not support that level of dynamic, conditional request routing.

It seems like you could fork this buildpack and in [`.buildpacks`](https://github.com/mars/create-react-app-buildpack/blob/master/.buildpacks) replace **heroku-buildpack-static** with a generalized Nginx buildpack like [generalassembly/nginx-buildpack](https://elements.heroku.com/buildpacks/generalassembly/nginx-buildpack). (Careful, there are a lot of Nginx buildpacks based on [heroku-nginx-buildpack](https://elements.heroku.com/buildpacks/heroku/heroku-buildpack-nginx) which are not a good fit for this purpose.)

With the GeneralAssembly Nginx buildpack, it is your app's responsibility to generate the raw `nginx.conf`, so the modifications you desire are possible.

Note of course the `static.json` config capabilities that come with **create-react-app-buildpack** will be removed when **heroku-buildpack-static** is replaced.

**Comment by knuhol** [comment]
Hey @luskin, did you resolve it somehow? I also need prerender and currently using this buildpack. Thanks!

**Comment by luskin** [comment]
@knuhol we migrated to Gatsby for a year or so and now have since migrated to Next.

**Comment by mars** [comment]
I strongly recommend [Next](https://nextjs.org/) too!

I haven't personally used this buildpack in years, because Next is such a better dev experience and significantly more capable.

**Comment by knuhol** [comment]
@luskin thanks! I have resolved it differently - have migrated my project to be served with Express which has very simple and officially supported [middleware](https://prerender.io/documentation/install-middleware#prerender-node) for prerender and using just default Heroku [Node.js buildpack](https://elements.heroku.com/buildpacks/heroku/heroku-buildpack-nodejs).
