### ISSUE TITLE
Redirect to HTTPS Possible?

### ISSUE THREAD

**Issue by adrice727** [mars/create-react-app-buildpack#12]
Is it possible to redirect all `http` requests to `https`?  This is typically done by checking the `x-forwarded-proto` header and redirecting as needed, but I'm not sure how things change with `create-react-app` .

**Comment by mars** [comment]
**HTTPS-only** is a customization option offered by the underlying static buildpack.
1. Create [`static.json` file](https://github.com/mars/create-react-app-buildpack#customization) at root of your repo
2. Set the [HTTPS only](https://github.com/heroku/heroku-buildpack-static#https-only) option

**Comment by adrice727** [comment]
Perfect.  Thank you!
