### ISSUE TITLE
Custom project root

### ISSUE THREAD

**Issue by afrankel-sfdo** [mars/create-react-app-buildpack#121]
Great build pack! 

I see that most of the scripts take `<build-dir>` as the first parameter, but how do you customize this? Basically, we have CRA as a subdirectory in our repository, so need to define a different root folder to kickoff the entire build process. Despite searching, wasn't able to find any info on this.

As-is the pack fails due to the initial `detect` assertion not being able to find our `package.json` located in the subdirectory.

```
-----> App not compatible with buildpack: https://github.com/mars/create-react-app-buildpack.git
       More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
 !     Push failed
```

Thanks!

**Comment by mars** [comment]
Hi @afrankel-sfdo 😃

In general, Heroku buildpacks do not work with non-root, sub-directory apps. It’s far more complicated than any sane person imagines at first. If you fork the buildpack and change things for your specific use-case, you might succeed, but will likely have to make compromises that tie your forked buildpack directly to your app structure.

The best solution is to put your app in its own repo at the root 😬

Next best solution is something like [this monorepo buildpack](https://github.com/lstoll/heroku-buildpack-monorepo/blob/master/README.md) that generalize for any buildpack/app combo.

**Comment by afrankel-sfdo** [comment]
@mars thanks for the quick response! Using the monorepo buildpack prior to running this one worked splendidly. Thanks again!
