### ISSUE TITLE
Directly going to non root route on first load = 404

### ISSUE THREAD

**Issue by rolandpeelen** [mars/create-react-app-buildpack#123]
I started using the buildpack and I have this app running that works fine with the regular (non builded version) when just pushing to heroku. Unfortunately, with the buildpack, when going directly to a url that is not the root (ie /x/:id for instance), I get a 404.

Example: https://bachkoor-v2-frontend-staging.herokuapp.com/events/5b88f17e551c85002c181932 

This is still running a free tier dyno, might take a bit to load

Any clue as to what is going wrong?

It seems that as soon as the page is loaded once, it can resolve through the service worker, but if it hasn't been, then it doesn't fetch it properly :)

**Comment by mars** [comment]
Hi @rolandpeelen 😄

Did you setup [URL routing](https://github.com/mars/create-react-app-buildpack/blob/master/README.md#user-content-routing-clean-urls)?

**Comment by rolandpeelen** [comment]
@mars -- Completely missed that one, so sorry. Thanks for the tip!
