### ISSUE TITLE
Proper way of using HEROKU_SLUG_COMMIT as a compile time constant

### ISSUE THREAD

**Issue by cancan101** [mars/create-react-app-buildpack#127]
I would like to use `HEROKU_SLUG_COMMIT` as a compile time constant. I am confused if I should follow https://github.com/mars/create-react-app-buildpack#user-content-add-on-config-vars as that mentions "set-up & use Runtime configuration to access the variables". Is there no way I can just access the constant as as constant? I'm not worried about that value changing between pipeline deploys as it is the git hash.

**Comment by mars** [comment]
This buildpack [exposes `REACT_APP_`, `NPM_`, & `NODE_` prefixed variables to the npm build process](https://github.com/mars/create-react-app-inner-buildpack/blob/master/bin/compile#L59), documented in the README [Architecture section](https://github.com/mars/create-react-app-buildpack/blob/master/README.md#user-content-architecture-).

So, use one of those three prefixes `REACT_APP_`, `NPM_`, or `NODE_` and it will be available during the build.

I'm also open to exposing `HEROKU_` prefix to the build process if one of the other prefixes does not work elegantly.

**Comment by cancan101** [comment]
The issue that I am having is that the [Dyno metadata](https://devcenter.heroku.com/articles/dyno-metadata) injects with that env var name so I don't control it. Maybe allow the `HEROKU_` prefix? Someone else had been asking about this awhile ago: https://github.com/mars/create-react-app-inner-buildpack/issues/6

**Comment by mars** [comment]
That makes sense @cancan101 , I will make that change, but cannot promise timing, so until then, the [Add-on config vars](https://github.com/mars/create-react-app-buildpack/blob/master/README.md#user-content-add-on-config-vars) technique should work to expose `HEROKU_` vars as `REACT_APP_HEROKU_` vars (or `NODE_HEROKU_` if you don't want the values embedded into the React app).

**Comment by cancan101** [comment]
In order to use the add on technique, I have to access it as a runtime var using your npm package?

**Comment by mars** [comment]
Gosh, sorry for the confusion. You're right that only works for runtime.

For buildtime, try changing your app's `package.json` `scripts.build` command to:

```json
{
  "scripts": {
    "build": "REACT_APP_HEROKU_SLUG_COMMIT=$HEROKU_SLUG_COMMIT react-scripts build"
  }
}
```

**Comment by cancan101** [comment]
will that work though or will the build pack keep that var from making it to the build command?

**Comment by mars** [comment]
You’re right, that won’t work either. Sorry I was really reaching to help you.

I guess the only fix is to add the `HEROKU_` prefix to the export list.

**Comment by cancan101** [comment]
What's the rationale for the build pack to maintain a white list of env var prefixes when rca already filters what is passed in to the build?

**Comment by mars** [comment]
It’s part of Heroku architecture for security. Things like database credentials & API keys are stored in config vars, and simply exposing everything by default would undermine trust in the platform.

**Comment by cancan101** [comment]
Perhaps allow for a config file to specify extra white listed env prefixes so that you don't need to make code changes for future additions?

**Comment by mars** [comment]
I think I can carve out the time this weekend to add support for `HEROKU_` vars & make a release, specifically to allow using dyno metadata in the build. Thanks for your patience & feedback @cancan101

**Comment by mars** [comment]
(Auto-closed from wrong PR)

**Comment by mars** [comment]
`HEROKU_` vars are now supported during build, as of v6.0.0.

[Please note](https://github.com/mars/create-react-app-buildpack/blob/master/README.md#user-content-compile-time-configuration) that:

Only `REACT_APP_` vars are replaced in **create-react-app**'s build. To make any other variables visible to React, they must be prefixed for the build command in `package.json`, like this:

```bash
REACT_APP_HEROKU_SLUG_COMMIT=$HEROKU_SLUG_COMMIT react-scripts build
```

If you're using the variables in your own build scripts/tooling, then the prefix should not be employed. Use `HEROKU_SLUG_COMMIT` directly.

**Comment by boertel** [comment]
When running the example above, it looks like `HEROKU_SLUG_COMMIT` **haven't** being setup to the newest value but contains the old git sha. Did anybody have more information about it ? and/or did anybody found a work around that?

**Comment by boertel** [comment]
Actually, `$SOURCE_VERSION` is the latest commit hash at compile time (https://github.com/mars/create-react-app-buildpack/issues/159)
