### ISSUE TITLE
Modifying static.json dynamically 

### ISSUE THREAD

**Issue by cancan101** [mars/create-react-app-buildpack#128]
More of a usage question, but perhaps could be in docs. Can the web process modify the static.json file before calling bin boot (ie at runtime,) ? Or has the nginx config been built at build time?

Right now I have certain routes that I only want active if certain env vars are set and would like to be able to leverage a pipeline to promote from dev to prod without having to recompile.

**Comment by mars** [comment]
Hi @cancan101 😄

Yes, the web process can modify the `static.json` file before calling `bin/boot`. That config file is read by `bin/boot` as it starts-up.
