### ISSUE TITLE
Private npm modules

### ISSUE THREAD

**Issue by CaryLandholt** [mars/create-react-app-buildpack#13]
When using private npm modules, you must provide an approved npm token.

Dynamically creating a `.npmrc` file during build on heroku would satisfy the need.

This is how I'm currently doing it.

`package.json`

``` json
"scripts": {
  "heroku-prebuild": "node ./scripts/setNpmrc.js",
}
```

`setNpmrc.js`

``` javascript
if (process.env.NODE_ENV !== 'production') {
  return
}

var fs = require('fs')

fs.writeFileSync('.npmrc', '//registry.npmjs.org/:_authToken=${REACT_APP_NPM_TOKEN}')
fs.chmodSync('.npmrc', 0600)
```

Then currently supported environment variable replacement would replace the placeholder with the actual token.

As the above does work, it would be nice if this were part of the build and perhaps configurable via `static.json` (`"private_npm_modules": true`).

I'm currently getting acclimated with heroku buildpacks so am not quite up to speed to submit a PR.

Thanks!

[some additional background](http://blog.npmjs.org/post/118393368555/deploying-with-npm-private-modules)

**Comment by mars** [comment]
Hi Cary, it looks like no script is required, `.npmrc` supports environment variable replacement: https://github.com/heroku/heroku-buildpack-nodejs/issues/174#issuecomment-136822505
