### ISSUE TITLE
Multiple CRAs in one repo, best way to deploy

### ISSUE THREAD

**Issue by weyert** [mars/create-react-app-buildpack#132]
I would like to share a common-ui library between two CRA applications and I am thinking of using Yarn Workspace to accomplish this. But now I am wondering how I can deploy the CRA applications using this build pack? I would like to run CRA separately for each other.

Currently, I am experimenting with: https://github.com/weyert/monorepo

**Comment by mars** [comment]
Hi @weyert,

Heroku’s build system is designed for one-app-per-repo. While there are ways to get monorepo projects to deploy as multiple apps, such as [a monorepo buildpack](https://github.com/lstoll/heroku-buildpack-monorepo), I recommend the app-per-repo approach for your use-case of sharing a common-ui library.

Publish the common-ui library to the npm registry (public or private) and then use it as a common dependency for seperate apps. You’ll end up with a more conventional, fewer surprises architecture, and have the benefit of a versioned common-ui package.
