### ISSUE TITLE
Failed to load resource errors (app in subdirectory)

### ISSUE THREAD

**Issue by kdjohnson89** [mars/create-react-app-buildpack#137]
I am receiving the following errors when trying to view my app using "heroku open" from Terminal:

[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (main.584fdd60.chunk.css, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (1.2d17499a.chunk.js, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (main.f0c6f50e.chunk.js, line 0)

The page is blank with just those errors in the console. Not sure what steps I need to take to resolve this? Appreciate the help.

Here is my build log:

Enumerating objects: 40, done.
Counting objects: 100% (40/40), done.
Delta compression using up to 4 threads
Compressing objects: 100% (39/39), done.
Writing objects: 100% (40/40), 143.86 KiB | 7.99 MiB/s, done.
Total 40 (delta 10), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> React.js (create-react-app) multi app detected
remote: -----> Configure create-react-app build environment
remote:        Using `NODE_ENV=development`
remote: =====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-multi.git
remote: =====> Detected Framework: Multipack
remote: =====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-nodejs.git
remote: =====> Detected Framework: Node.js
remote:        
remote: -----> Creating runtime environment
remote:        
remote:        NPM_CONFIG_LOGLEVEL=error
remote:        NPM_CONFIG_PRODUCTION=false
remote:        NODE_ENV=development
remote:        NODE_MODULES_CACHE=true
remote:        NODE_VERBOSE=false
remote:        
remote: -----> Installing binaries
remote:        engines.node (package.json):  unspecified
remote:        engines.npm (package.json):   unspecified (use default)
remote:        
remote:        Resolving node version 8.x...
remote:        Downloading and installing node 8.12.0...
remote:        Using default npm version: 6.4.1
remote:        
remote: -----> Building dependencies
remote:        Installing node modules (package.json + package-lock)
remote:        added 1717 packages from 769 contributors and audited 32111 packages in 54.924s
remote:        found 0 vulnerabilities
remote:        
remote:        
remote: -----> Caching build
remote:        - node_modules
remote:        
remote: -----> Pruning devDependencies
remote:        Skipping because NODE_ENV is not 'production'
remote:        
remote: -----> Build succeeded!
remote: =====> Downloading Buildpack: https://github.com/mars/create-react-app-inner-buildpack.git
remote: =====> Detected Framework: React.js (create-react-app)
remote:        Writing `static.json` to support create-react-app
remote:        Enabling runtime environment variables
remote: 
remote: > neighborhood-app@0.1.0 build /tmp/build_17588575619d7d50f20d50e88cef0b5f
remote: > react-scripts build
remote: 
remote: Creating an optimized production build...
remote: Compiled successfully.
remote: 
remote: File sizes after gzip:
remote: 
remote:   63.55 KB  build/static/js/1.2d17499a.chunk.js
remote:   3.28 KB   build/static/js/main.f0c6f50e.chunk.js
remote:   776 B     build/static/js/runtime~main.3ab0154c.js
remote:   531 B     build/static/css/main.584fdd60.chunk.css
remote: 
remote: The project was built assuming it is hosted at /neighborhood-app/.
remote: You can control this with the homepage field in your package.json.
remote: 
remote: The build folder is ready to be deployed.
remote: To publish it at https://kdjohnson89.github.io/neighborhood-app, run:
remote: 
remote:   npm run deploy
remote: 
remote: Find out more about deployment here:
remote: 
remote:   http://bit.ly/CRA-deploy
remote: 
remote: =====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-static.git
remote: =====> Detected Framework: Static HTML
remote:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
remote:                                  Dload  Upload   Total   Spent    Left  Speed
remote:   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--remote: 100  838k  100  838k    0     0  12.4M      0 --:--:-- --:--:-- --:--:-- 12.4M
remote: -----> Installed directory to /app/bin
remote: Using release configuration from last framework (Static HTML).
remote: -----> Discovering process types
remote:        Procfile declares types     -> (none)
remote:        Default types for buildpack -> web
remote: 
remote: -----> Compressing...
remote:        Done: 69.5M
remote: -----> Launching...
remote:        Released v3
remote:        https://guarded-inlet-77003.herokuapp.com/ deployed to Heroku
remote: 
remote: Verifying deploy... done.
To https://git.heroku.com/guarded-inlet-77003.git
 * [new branch]      master -> master

**Comment by mars** [comment]
Hi @kdjohnson89 😄

I just tried opening your app in my browser too. I see the errors. Specifically, the **404** not found errors are reported for URLs like this one:

```
https://guarded-inlet-77003.herokuapp.com/neighborhood-app/static/js/1.2d17499a.chunk.js
```

Based on that URL, it appears that your app is contained in a `neighborhood-app/` directory in the git repo, but Heroku does not support apps in sub-directories.

The contents of `neighborhood-app/` must be moved into the root (top-level) of the repo. These commands should do it:

```bash
# Move normal files & directories
git mv neighborhood-app/* ./
# Move dotfiles
git mv neighborhood-app/.* ./
# Remove the empty directory
rmdir neighborhood-app
# Commit the new layout
git add .
git commit -m 'Move app to root to fix Heroku deployment'
```

**Comment by kdjohnson89** [comment]
Thank you for the quick response @mars! I tried the first command and received the following response: 

Kaylas-iMac:neighborhood-app kaylajohnson$ git mv neighborhood-app/* ./
fatal: bad source, source=neighborhood-app/*, destination=*

**Comment by kdjohnson89** [comment]
Thank you 😊
