### ISSUE TITLE
error: failed to push some refs 

### ISSUE THREAD

**Issue by alphafhb** [mars/create-react-app-buildpack#143]
Please help me Mars. I followed your video step by step and also tryed with myself but I can't finally deploy my application to heroku. 
```
MacBooks-MacBook-Air:makesensify hello$ git push heroku master
Counting objects: 86, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (84/84), done.
Writing objects: 100% (86/86), 924.39 KiB | 9.94 MiB/s, done.
Total 86 (delta 8), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> App not compatible with buildpack: https://github.com/findforhad/findforhad-makesensify.git
remote:        bash: /app/tmp/buildpacks/0dc72b559bd1e0a66cca33fb640d953d3a9a4688184a0224740ee92c5a6bb854b238fb59087de9809e4e309c6f9bebb3eb006c7bb5a32d8b973a4b4f1ee71e76/bin/detect: No such file or directory
remote: 
remote:        More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !	Push rejected to makesensify.
remote: 
To https://git.heroku.com/makesensify.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/makesensify.git'
```

**Comment by mars** [comment]
Hi @findforhad,

I did not produce a video. I do not know what was done to get to this place.

That build error means that `package.json` is not at the root of the git repo (project directory). My guess is that the React app is either not in the root directory,  or not committed in git.

Please follow the [Usage instructions](https://github.com/mars/create-react-app-buildpack/blob/master/README.md#user-content-usage) to figure out what you might have missed.

Let me know how it goes! 😄

**Comment by alphafhb** [comment]
Finally, I hosted my application in firebase. It was a firebase project.
you can visit on my application on this link
https://makesensify-2.firebaseapp.com
