### ISSUE TITLE
Build failed remote  - Two different lockfiles found: package-lock.json and yarn.lock

### ISSUE THREAD

**Issue by chrisdel101** [mars/create-react-app-buildpack#148]
I did have two files, and I removed the yarn following the directions, using `git rm yarn.lock` then committed. I also read these https://stackoverflow.com/questions/47238241/heroku-build-failing-due-to-yarn-and-npm-lockfile-conflict and https://stackoverflow.com/questions/53646679/heroku-not-allow-me-deploy-the-project-as-i-follow-the-instruction-but-not-work

I still get the error and no other info on how solve it. 

<img width="227" alt="screen shot 2019-01-10 at 2 14 23 pm" src="https://user-images.githubusercontent.com/14151974/50991199-1b053000-14e2-11e9-8bc6-66c92cbaf50d.png">

Oh, and  https://kb.heroku.com/why-is-my-node-js-build-failing-because-of-conflicting-lock-files

**Comment by mars** [comment]
I'm not familiar with conflicting lock files; always use npm.

Barring that there's been a mistake and both lockfiles actually do still exist in the commit you're pushing to Heroku, I can only think to reset the app's Heroku git repo, which includes the build cache.

Install the Heroku CLI [Repo plugin](https://github.com/heroku/heroku-repo), and run:

```bash
heroku repo:reset -a appname
```

Then try `git push heroku master` again.

**Comment by mars** [comment]
Another thing that could be causing this confusion:  
**Are you pushing the correct branch to Heroku?**

The typical command pushes master to master:

```bash
git push heroku master
```

If you're working on a branch, and want to deploy that branch, then do:

```bash
git push heroku branchname:master
```

**Comment by chrisdel101** [comment]
Thanks! This worked to solve part of the problem.. However the page is blank and I have the errors `Uncaught SyntaxError: Unexpected token <` and `Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.`

**Comment by mars** [comment]
To help debug your app code, check the app’s logs: `heroku logs -t -n 1500`
