### ISSUE TITLE
PUBLIC_URL has no effect

### ISSUE THREAD

**Issue by stevehanson** [mars/create-react-app-buildpack#149]
I am trying to serve my assets from a CDN. Based on the Create React App [Advanced Configuration documentation](https://facebook.github.io/create-react-app/docs/advanced-configuration), `PUBLIC_URL` seems to be the way to do that:

> Create React App assumes your application is hosted at the serving web server's root or a subpath as specified in package.json (homepage). Normally, Create React App ignores the hostname. You may use this variable to force assets to be referenced verbatim to the url you provide. This may be particularly useful when using a CDN to host your application.

I have set `PUBLIC_URL` on Heroku and redeployed my application, but it seems to have no effect. I also saw [this issue thread](https://github.com/mars/create-react-app-buildpack/issues/19#issuecomment-257731475) in which it was mentioned that `PUBLIC_URL` is disabled for this buildpack:

> Note that %PUBLIC_URL% will always be empty on Heroku. Root-relative paths work correctly with this buildpack, so PUBLIC_URL it is ignored. (Although, I'm open to adding PUBLIC_URL support if it's needed for an unforeseen use-case.)

Curious if there is a different recommended approach for serving assets from a CDN or if there is a way for me to enable `PUBLIC_URL`. Thanks!

**Update:** Because I've ejected from Create React App, I was able to work around this for now by replacing `process.env.PUBLIC_URL` in the CRA build process with `process.env.NODE_PUBLIC_URL` and using that ENV variable on Heroku.

**Comment by mars** [comment]
Yes, indeed you solved the problem 🤔🍪

For environment variables to be visible to this buildpack's compile phase, they must prefixed with `REACT_APP_`, `NODE_`, `NPM_`, or `HEROKU_`.

[As documented for **Compile-time config**](https://github.com/mars/create-react-app-buildpack/blob/master/README.md#user-content-compile-time-configuration) 📚

Note that if you want the app's config value to update for every release (not requiring a rebuild), then you'd need to use [Runtime config](https://github.com/mars/create-react-app-buildpack/blob/master/README.md#user-content-runtime-configuration) instead, along with the `REACT_APP_` prefix.
