### ISSUE TITLE
SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by khlj** [mars/create-react-app-buildpack#15]
Hi,
I have following error (it's just one of them) :

```
2016-10-20T00:56:26.841908+00:00 app[web.1]: /app/src/index.js:1
2016-10-20T00:56:26.841922+00:00 app[web.1]: (function (exports, require, module, __filename, __dirname) { import React from 'react';
2016-10-20T00:56:26.841923+00:00 app[web.1]:                                                               ^^^^^^
2016-10-20T00:56:26.841923+00:00 app[web.1]: 
2016-10-20T00:56:26.841924+00:00 app[web.1]: SyntaxError: Unexpected token import
2016-10-20T00:56:26.841925+00:00 app[web.1]:     at exports.runInThisContext (vm.js:53:16)
2016-10-20T00:56:26.841925+00:00 app[web.1]:     at Module._compile (module.js:387:25)
2016-10-20T00:56:26.841926+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:422:10)
2016-10-20T00:56:26.841927+00:00 app[web.1]:     at Module.load (module.js:357:32)
2016-10-20T00:56:26.841927+00:00 app[web.1]:     at Function.Module._load (module.js:314:12)
2016-10-20T00:56:26.841928+00:00 app[web.1]:     at Function.Module.runMain (module.js:447:10)
2016-10-20T00:56:26.841928+00:00 app[web.1]:     at startup (node.js:148:18)
2016-10-20T00:56:26.841929+00:00 app[web.1]:     at node.js:405:3
```

And my package.json file is :

```
{
  "name": "reactMasp",  
  "version": "0.1.0",  
  "private": true,
  "devDependencies": {
    "babel-preset-node5": "^11.1.0",
    "babel-preset-node6": "^11.0.0",
    "babel-preset-react": "^6.16.0",
    "react-scripts": "0.6.1"
  },
  "dependencies": {
    "firebase": "^3.5.0",
    "googlemaps": "^1.11.1",
    "react": "^15.3.2",
    "react-dom": "^15.3.2",
    "react-forms": "^2.0.0-beta33",
    "react-google-maps": "^6.0.1",
    "react-modal": "^1.5.2",
    "react-native": "^0.35.0",
    "react-native-modal": "^0.4.0",
    "react-scripts": "^0.6.1",
    "reactfire": "^1.0.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  },
  "description": "This project was bootstrapped with [Create React App](https://github.com/facebookincubator/create-react-app).",
  "main": "index.js",
  "repository": {
    "type": "git",
    "url": "git+https://my_github_repo"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "bugs": {
    "url": "https://my_github_repo/issues"
  },
  "homepage": "https://my_github_repo"
}
```

Do you know what I might be missing?
I'm really new to react, heroku, and web dev, and can't seem to figure out how to resolve...
Thanks!

**Comment by mars** [comment]
Hi @hshin23, welcome to React + Heroku 😄

The `Unexpected token import` error indicates that ES6 module syntax `import` is not understood. **ES6 modules normally just work with create-react-app**, so there's something suspicious going on with this app's code.

First, it's always easier to debug locally, on your own computer. Does this app run locally with `npm start` and build with `npm run build`?

Second, I see several babel presets have been added, none of which will add value to create-react-app. In fact those are probably causing the error. Try removing them with `npm uninstall --save-dev babel-preset-node5 babel-preset-node6 babel-preset-react`, and then confirm that [importing a component](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#importing-a-component) works as intended.

Remember to test with `npm start` locally, then `git add .` + `git commit` the changes before pushing to Heroku.

**Comment by mars** [comment]
Also, combining React Native and a React web project is a quite advanced topic. Simply having it required into your production dependencies will inflate the bundle/download size and potentially cause issues like you're experiencing.

`npm uninstall react-native react-native-modal --save` will help you here.

**Comment by khlj** [comment]
Hi @mars !
Thanks for clarifying the issue, getting to know that there might be some sort of compatibility issue is a lot!
First off, my app works fine on local server when started with `npm start`. I'm also suspecting that there might be something wrong with my Procfile.

And, I need to set up jest along with the create-react-app, and according to the tutorial from [jest](https://facebook.github.io/jest/docs/tutorial-react.html#content),
it says to install some babel-presets with
`npm install --save-dev jest babel-jest babel-preset-es2015 babel-preset-react react-test-renderer`

Should I ignore babel-preset-es2015 and babel-preset-react and just install babel-jest and react-test-renderer, or is babel-jest not needed as well?

**Comment by mars** [comment]
The most recent version of create-react-app includes a [Jest runner](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#running-tests)!

Make sure `"react-scripts": "0.6.1"` in package JSON. Follow any breaking changes migrations in the [release notes](https://github.com/facebookincubator/create-react-app/blob/master/CHANGELOG.md#061-september-27-2016).

**Comment by mars** [comment]
`"react-scripts": "0.7.0"` is now available with improved Jest testing support.

https://github.com/facebookincubator/create-react-app/releases/tag/v0.7.0
