### ISSUE TITLE
README update re: Heroku's build process changes

### ISSUE THREAD

**Issue by ekilah** [mars/create-react-app-buildpack#155]
blog post: https://devcenter.heroku.com/changelog-items/1557
Extended FAQ: https://help.heroku.com/P5IMU3MP/heroku-node-js-build-script-change-faq

As far as I can tell, users of this repo will need to tell Heroku to skip running `npm run build` for them, because this buildpack takes care of that. Heroku's FAQ is pretty nice above, I'm suggesting a link out to it and/or a quick blurb in the README to say users should include `heroku-postbuild` in their `package.json`'s `scripts`, as Heroku suggests.

**Comment by jmorrell** [comment]
👋 Hi, I wrote the FAQ and made the change

My hope is that once the buildpack is executing the `build` script, that this buildpack can do less work. If there's some issue with that I'm happy to help figure out a work-around.

**Comment by ekilah** [comment]
:wave: 
To be honest, I inherited the build setup on the project I'm working on, so I'm not intimately familiar with which pieces are _supposed_ to do which bits. but a change like that would require some messaging if other users of this repo are doing what I understood I should do, which is to tell Heroku to no longer run `npm run build` for me

**Comment by mars** [comment]
Hi folks 🤓 Revising this buildpack for the new build process is on my list to work on very soon. I’ll update with a testable PR when it’s ready 🙌

**Comment by mars** [comment]
Ready for testing ➡️  #156
