### ISSUE TITLE
environment variables are persisted when artifacts are promoted through Heroku CI

### ISSUE THREAD

**Issue by brandonkirchner** [mars/create-react-app-buildpack#160]
when you promote a change from one environment to another (stage to prod, for example), the environment variables set in stage will be set in prod, overriding whatever the environment variables are in prod. to fix, you need to re-build and deploy from prod.

**Comment by mars** [comment]
Hi @brandonkirchner 🙂

See [Runtime config variables](https://github.com/mars/create-react-app-buildpack/blob/master/README.md#user-content-compile-time-vs-runtime), a feature created specifically for this buildpack that eliminates the re-build step by injecting variables into the Javascript bundle as each Heroku dyno starts-up.
