### ISSUE TITLE
README.md needs to be updated.

### ISSUE THREAD

**Issue by aarona** [mars/create-react-app-buildpack#163]
In the "Quick Start" section before you push the initial changes to heroku for the first time, you need to have a `yarn.lock` file included in the project. The build fails and suggests running the following commands before doing this:

```
yarn install
git add yarn.lock
git commit -m "Updated Yarn lockfile"
git push heroku master
```

**Comment by mars** [comment]
Thanks for mentioning this, but the instructions are for using`npm` not `yarn`.

We currently assume that Yarn is a non-standard tooling choice. So it’s up to the developer such as yourself to swap it in where it’s needed.

**Comment by aarona** [comment]
Got it! Good to know.
