### ISSUE TITLE
Build runs twice

### ISSUE THREAD

**Issue by dcporter44** [mars/create-react-app-buildpack#168]
Heroku has recently started executing `build` automatically:
https://devcenter.heroku.com/changelog-items/1557

This means that when using this buildpack, `build` is run two times. Once by Heroku and once by this buildpack.

If you add `"heroku-run-build-script"=false` to `package.json`, it will prevent Heroku from running automatically.

This should be added to the documentation of this buildpack.

**Comment by mars** [comment]
Hi @dcporter44 😃 Thanks for the feedback.

*That change happened almost a year ago*, and we already performed the transition on this buildpack.

If you're seeing two `build` runs, then there's probably something else going on with your app. Do you have other pre or post build scripts in your `package.json` that would trigger another build?

**Comment by dcporter44** [comment]
I'm actually noticing that `"heroku-run-build-script"=false` is actually not doing anything and its still building twice :(

I havent messed with the package.json file at all. I'm using it straight out of the box from latest CRA version

**Comment by mars** [comment]
I just created an new app with create-react-app 3.4.0 (current as of now), pushed it to a new Heroku app with this buildpack, **the build ran once**, and it started-up healthy 👍

What does `heroku buildpacks` return for your app?

What are the contents of the `package.json`?

**Comment by mars** [comment]
My guess is that either your app has the buildpack set twice (maybe as two different identifiers) or that there’s a pre or post install script performing build again.

Not an issue with this buildpack itself.

**Comment by dcporter44** [comment]
Hey, I figured it out. I also had the heroku/node buildpack added on my app. I just removed that and now it's only running once. 👍
