### ISSUE TITLE
How to configure Fastly CDN?

### ISSUE THREAD

**Issue by debotos** [mars/create-react-app-buildpack#170]
How do I configure Fastly CDN service?

**Comment by mars** [comment]
1. Follow [Fastly's quick start guide](https://docs.fastly.com/en/guides/start-here)
2. Set the **Origin Server** host to your Heroku app's built-in hostname
    * for example `my-app.herokuapp.com`
3. Profit!

(Note that I have never used Fastly. I just looked up their documentation.)
