### ISSUE TITLE
Is there a way to enable Gzip compression ?

### ISSUE THREAD

**Issue by boolangery** [mars/create-react-app-buildpack#171]
Hi,

See above :)

Thanks

**Comment by mars** [comment]
As far as I can tell, responses are already encoded with `gzip` when appropriate.

<img width="911" alt="Screen Shot 2020-04-03 at 4 13 49 PM" src="https://user-images.githubusercontent.com/17164/78411882-2a303c00-75c6-11ea-8a2f-44b4c426fe13.png">
