### ISSUE TITLE
When using Runtime env-variables, className of toggled element is swapped for the className of the element directly underneath it.

### ISSUE THREAD

**Issue by davidrouten** [mars/create-react-app-buildpack#172]
This is hard to explain; @mars feel free to ping me if you have questions or need other information! (And thank you a ton for this functionality!).

### Our basic issue:
We would like to use an ENV as a switch to show/hide a banner at the top of the page. We'd like this toggle to work without having to rebuild the app (why we are using the Runtime-env-variable library recommended in this buildpack).

### The problem:
Using that library worked well to show/hide the banner. Unfortunately, for some reason I was not able to find, when we set the ENV variable and restart the server, the banner shows BUT its className is being replaced with the className of the element directly below it (`<Header />`) which seems bizarre. **This code works perfectly locally but breaks on staging.**

_We can just add a simple PR to add the banner and add another one to remove it at the end of the month as needed; this issue isn't holding us up, it was just very odd and thought I should share in case this is some kind of obscure bug._

### Now on to the relevant code:

```
heroku buildpacks -a heroku-brand-staging
=== heroku-brand-staging Buildpack URL
https://github.com/mars/create-react-app-buildpack.git
```

- Code is deployed to the staging app currently through a branch `dr/add-runtime-env-config-functionality`.
- Can be accessed at: https://heroku-brand-staging.herokuapp.com/.
- Build logs can be shared if necessary.

Code in main `App/index.js` file:
```
class App extends Component {
  render () {
    const env = runtimeEnv();
    ...

    return (
      <div className='App'>
        <PrideBanner visible={env.REACT_APP_PRIDE_BANNER === 'true'} />
        <Header />
...
```

Code in `PrideBanner/index.js file:`
```
import React from 'react'
import './PrideBanner.css'

const PrideBanner = (props) => {
  return props.visible ? (
    <div onClick={void(0)} className='pride-banner'>
      <div className='pride-wrapper'>
        <p> Heroku supports our LGBTQ employees, customers, and the wider community.</p>
      </div>
    </div>
  ) : (
    null
  )
}

export default PrideBanner
```

**What we expect to see in the console/what we see locally:**
```
<div class="pride-banner">
  <div class="pride-wrapper">
    <p> Heroku supports our LGBTQ employees, customers, and the wider community.</p>
  </div>
</div>
<div class="loaded Header pt7 bg-gradient-secondary">
  ...
```

**What we ACTUALLY see in staging:**
```
<div class=" Header pt7 bg-gradient-secondary">
  <div class="pride-wrapper">
    <p> Heroku supports our LGBTQ employees, customers, and the wider community.</p>
  </div>
</div>
<div class="loaded Header pt7 bg-gradient-secondary">
  ...
```

Logs on restart:
```
2020-05-26T16:59:10.969385+00:00 heroku[web.1]: Restarting
2020-05-26T16:59:10.972415+00:00 heroku[web.1]: State changed from up to starting
2020-05-26T16:59:12.342111+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2020-05-26T16:59:12.388536+00:00 app[web.1]: Going down, terminating child processes...
2020-05-26T16:59:12.467450+00:00 heroku[web.1]: Process exited with status 0
2020-05-26T16:59:17.495092+00:00 heroku[web.1]: Starting process with command `bin/boot`
2020-05-26T16:59:20.135865+00:00 app[web.1]: Injecting runtime env into /app/build/static/js/main.ee1f17ae.js (from .profile.d/inject_react_app_env.sh)
2020-05-26T16:59:20.778893+00:00 app[web.1]: Starting log redirection...
2020-05-26T16:59:20.779362+00:00 app[web.1]: Starting nginx...
2020-05-26T16:59:21.834578+00:00 heroku[web.1]: State changed from starting to up
```

**Comment by mars** [comment]
Hi @davidrouten,

I don't see how this is an error with the environment variables. There's literally nothing that env vars have to do with React element rendering. Such a rendering bug seems very much in React's court.

Maybe it becomes evident in the React production build? When you say "it works locally", do you mean using dev mode (`npm run dev`) or production build (`npm run build && npm run start`)?

**Comment by davidrouten** [comment]
Thanks Mars; React is most likely the culprit, was really hoping someone had run into a similar issue to this before, but this is probably not the best place to check!

Will close and thank you for the prompt review and feedback :)
