### ISSUE TITLE
deployment build fails to find react-scripts

### ISSUE THREAD

**Issue by paulwalker** [mars/create-react-app-buildpack#18]
In a dokku (https://github.com/dokku/dokku) enviornment, it does not appear to install devDependencies, so the build fails when attempting to run `react-scripts build`. I guess Heroku installs devDepencies? I'm not sure if dokku is non-standard here or Heroku, but moving the react-scripts to `dependencies` from `devDependencies` worked for me.

Not sure if this an issue I should file with create-react-app or dokku :-/.

**Comment by coding102** [comment]
^ Helped me 👍

**Comment by mars** [comment]
`NPM_CONFIG_PRODUCTION=false` is set throughout the entire build, so the **heroku/nodejs** buildpack will install devDependencies too:
https://github.com/mars/create-react-app-buildpack/blob/master/bin/compile#L36

This works on Heroku. Unsure what the difference is for Dokku. Do env variables work differently during Dokku build?
