### ISSUE TITLE
Build Error 

### ISSUE THREAD

**Issue by katwingki** [mars/create-react-app-buildpack#180]
I already moved everything under src directory based on the logs suggested but it is still not working 

GIT HUB REPO: https://github.com/katwingki/priscillaWeddingGreetings
BUILD LOGs:
-----> React.js (create-react-app) multi app detected
=====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-multi.git
=====> Detected Framework: Multipack
=====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-nodejs.git
=====> Detected Framework: Node.js
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       NODE_VERBOSE=false
       
-----> Installing binaries
       engines.node (package.json):  12.18.3
       engines.npm (package.json):   6.14.6
       
       Resolving node version 12.18.3...
       Downloading and installing node 12.18.3...
       npm 6.14.6 already installed with node
       
-----> Installing dependencies
       Installing node modules (package.json)
       
       > core-js@2.6.11 postinstall /tmp/build_adee47f4/node_modules/core-js
       > node -e "try{require('./postinstall')}catch(e){}"
       
       
       > core-js-pure@3.6.5 postinstall /tmp/build_adee47f4/node_modules/core-js-pure
       > node -e "try{require('./postinstall')}catch(e){}"
       
       
       > ejs@2.7.4 postinstall /tmp/build_adee47f4/node_modules/ejs
       > node ./postinstall.js
       
       
       > core-js@3.6.5 postinstall /tmp/build_adee47f4/node_modules/react-app-polyfill/node_modules/core-js
       > node -e "try{require('./postinstall')}catch(e){}"
       
       added 1903 packages from 782 contributors and audited 1907 packages in 59.624s
       
       117 packages are looking for funding
         run `npm fund` for details
       
       found 0 vulnerabilities
       
       
-----> Build
       Running build
       
       > priscilla-wedding-website@0.1.0 build /tmp/build_adee47f4
       > react-scripts build
       
       Creating an optimized production build...
       Failed to compile.
       
       ./src/component/Home.js
       Cannot find file './MainSection.js' in './src/component'.
       
       
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! priscilla-wedding-website@0.1.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the priscilla-wedding-website@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/npmcache.ZuN92/_logs/2020-11-06T06_08_32_698Z-debug.log
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       If you're stuck, please submit a ticket so we can help:
       https://help.heroku.com/
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile React.js (create-react-app) multi app.
 !     Push failed

**Comment by ArturoMorales93** [comment]
The same thing is happening to me right now. Is this an issue or how we fix it?

**Comment by mars** [comment]
The error is right there in the logs you pasted:

```
   ./src/component/Home.js
   Cannot find file './MainSection.js' in './src/component'.
```

Perhaps the capitalization of `./MainSection.js` does not match what is committed to git?
