### ISSUE TITLE
Serving a json file

### ISSUE THREAD

**Issue by ggoldens** [mars/create-react-app-buildpack#19]
Hi! I'm looking a way to serve a file that I have in the root of my project. The name of this file is `apple-app-site-association` that is basically a json file.

Just need to return the content of this file launching the absolute GET url e.g. 'https://mydomain.com/apple-app-site-association'

I tried adding the route in the static.json file but nothing.

```
{
  "root": "build/",
  "clean_urls": false,
  "routes": {
  	"/apple-app-site-association": "apple-app-site-association"
  },
  "https_only": true
}
```

But it is returning 404.

How can I achieve this?

Thanks!

**Comment by mars** [comment]
Hello @ggoldens !

No changes to `static.json` are required.

Add files to the `public/` directory of the project, and they'll be available at the root of the web site.

See the [create-react-app docs](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#using-the-public-folder) for more info about this feature. Note that `%PUBLIC_URL%` will always be empty on Heroku. Root-relative paths work correctly with this buildpack, so `PUBLIC_URL` it is ignored. (Although, I'm open to adding `PUBLIC_URL` support if it's needed for an unforeseen use-case.)

**Comment by ggoldens** [comment]
Thank you @mars!! worked perfectly!

**Comment by Faisalnawaz953** [comment]
> Thank you @mars!! worked perfectly!

@mars how its worked?I am stucked in same issue
