### ISSUE TITLE
configuring a proxy

### ISSUE THREAD

**Issue by perNyfelt** [mars/create-react-app-buildpack#191]
The proxy configuration behaves slightly different than the react proxy config in package.json.

In the example configuration i.e.
```json
"proxies": {
    "/api/": {
      "origin": "${API_URL}"
    }
  }
```
The setting of the API_URL variable is given the example of 
```
heroku config:set API_URL="https://backend.example.com"
```
This means a url such as `/api/login` will be `https://backend.example.com/login`.
Most likely the backend url would correspond to what has been tested locally and thus end with /api. If the API_URL instead would be set to 
```
heroku config:set API_URL="https://backend.example.com/api"
```
Then a call to `/api/login` would become `https://backend.example.com/api/login` which is probably more intuitive.

It would be nice to mention this in the readme.md#user-content-proxy

**Comment by mars** [comment]
This is already documented in [Proxy URL config](https://github.com/mars/create-react-app-buildpack#proxy-url-prefix) section of the README documentation.
