### ISSUE TITLE
Where can I find/how can I edit nginx.config.erb?

### ISSUE THREAD

**Issue by astewes** [mars/create-react-app-buildpack#194]
I recently deployed my React website to Heroku and am needing to edit nginx.config.erb. Where can I find this file and how can I make edits to it?

**Comment by mars** [comment]
Nginx config is not directly editable. The only Nginx modifications supported are through the static buildpack's `static.json` config file:

https://github.com/mars/create-react-app-buildpack/blob/master/README.md#web-server
