### ISSUE TITLE
Not specific to create react app

### ISSUE THREAD

**Issue by InsidersByte** [mars/create-react-app-buildpack#2]
Thanks for the awesome buildpack!

I know this is stated as the create react app buildpack, but it is useful for other react apps. 

I am currently using it on my own react app and the requirements are that it needs to be static and that it has `build` command which runs webpack (or browserify I guess).

**Comment by mars** [comment]
Great to hear that it's working for your non-`create-react-app` app.

It's true today, all this buildpack relies on is:
- `npm run build` performs the transpile/bundling
- the file `build/index.html` exists at runtime

It's possible these specs will change as `create-react-app` evolves, but its utility as a general purpose SPA deployer is a welcome perspective 🤔

Thanks for the kind issue 🌟😄

**Comment by InsidersByte** [comment]
I was thinking the same about a general purpose SPA deployer! If more functionality is added to `create-react-app` then functionality could be added to it.

The `index.html` just has to exist at the `root` set in `static.json`.
