### ISSUE TITLE
Heroku Slug Size 50mb

### ISSUE THREAD

**Issue by Jony-Y** [mars/create-react-app-buildpack#22]
Hi, I just started my new project and have about 4 flows, no images no videos and of course am using the create react app boilerplate, I pushed the code to heroku according to the instructions but the slug size seems huge to me. its 50+mb 
is this normal?

pushing to heroku came from the project folder and not from the build folder. that is correct isnt it?

**Comment by mars** [comment]
The slug size output from this buildpack is mostly due to the `node_modules/` directory which is populated by npm installing both production & dev dependencies.

**Comment by Jony-Y** [comment]
@mars ok, so thats normal for the boilerplate? 
and should we push the entire project to heroku and not just the build folder? If I understood correctly, we push the entire project and the buildpack runs the build itself and runs the compiled code right?

**Comment by mars** [comment]
Yes, this is normal. This buildpack is made to receive the whole git repo and perform the build from the root level based on `package.json`.

**Comment by Jony-Y** [comment]
ok, thanks :) closing
