### ISSUE TITLE
Building app does not work with yarn

### ISSUE THREAD

**Issue by vaclavbohac** [mars/create-react-app-buildpack#23]
Deploying a react app with `yarn.lock` fails to compile the app as yarn ignores the `NPM_CONFIG_PRODUCTION` flag and omits the dev dependencies necessary to run the webpack.

There's a simple workaround as all you need to do is to delete `yarn.lock` file from the project and the build scripts will fall back to the `npm` (https://github.com/heroku/heroku-buildpack-nodejs/blob/v93/bin/compile#L54). But that't not what you really want to do

**Comment by gaearon** [comment]
Should the be filed with Yarn?

**Comment by mars** [comment]
The underlying Node buildpack recently [added Yarn support](https://devcenter.heroku.com/changelog-items/1065), so I imagine this should not be too difficult to get working 🤞

How does one [for devDeps to install with Yarn](https://yarnpkg.com/en/docs/cli/install#yarn-install---production-a-classtoc-idtoc-yarn-install-production-hreftoc-yarn-install-productiona)? Looks like `NODE_ENV` needs to be set to `development` during build in the [inner buildpack](https://github.com/mars/create-react-app-inner-buildpack/blob/master/bin/compile).

I'm traveling for the holidays and will not have a chance to investigate immediately.

**Comment by mars** [comment]
It's possible that setting that config/env var manually will prove the fix:

```
heroku config:set NODE_ENV=development

# then redeploy
git push heroku master
```

If that works, then I will update the underlying buildpack compile to automate this step during `npm build`

**Comment by laduke** [comment]
Didn't deploy something for a couple days and this happened to me too. Thanks for the thread. 

`heroku config:set NODE_ENV=development`

worked for me. Not sure what the proper yarn solution would be.

**Comment by Aadmaa** [comment]
"heroku config:set NODE_ENV=development" worked for me too. For clarity ... if folks are starting a brand new web app right now and you are looking at this --  https://blog.heroku.com/deploying-react-with-zero-configuration -- for deployment instructions, add the step as shown below, or deployment to Heroku fails.

npm install -g create-react-app
create-react-app my-app
cd my-app
git init
heroku create -b https://github.com/mars/create-react-app-buildpack.git
git add .
git commit -m "react-create-app on Heroku"

**// ADD to your process here:**
**heroku config:set NODE_ENV=development**

git push heroku master
heroku open

**Comment by mars** [comment]
Just released [support for yarn](https://github.com/mars/create-react-app-buildpack/releases/tag/v4.0.0) in this buildpack, so no special configuration is required to use yarn.

**Comment by gaearon** [comment]
Thank you!
