### ISSUE TITLE
Is there a way to specify the directory of the create-react-app app?

### ISSUE THREAD

**Issue by ijsnow** [mars/create-react-app-buildpack#25]
So this may be an edge case that I have created. What I am doing is writing a component library and then a documentation site for the library. I may have to go to something like AWS to make things easier but using heroku would make my workflow much cleaner. The project setup is roughly as follows:

```
.git
package.json // (for component library)
src // (component library source)
dist // (directory for built/transpiled components in library)
docs // (directory for documentation site created with 'create-react-app')
 \   package.json
     src // (documentation site source code)
     build // (built/transpiles create-react-app)
```

I don't know much about how buildpacks are put together but I did notice you [specifying some `*_DIR` variables here](https://github.com/mars/create-react-app-buildpack/blob/master/bin/compile#L21). Is there a way for me to specify where the `package.json` /`node_modules` are for the app I'm actually deploying? Or preferably being able to just do something that would tell heroku to `cd docs` before building? I already have the root set to `docs/build/` in my `static.json` as shown [here](https://github.com/mars/create-react-app-buildpack#web-server).

Thanks in advance for any feedback!

EDIT to add more info:
I changed the `build` script to build the app in `docs` and as mentioned above changed the root to point to the right directory as told to do [here](https://github.com/mars/create-react-app-buildpack#general-purpose-spa-deployment).

The error I'm getting is that `react-scripts` can't be found but I have a feeling thats because its actually installing the dependencies from the root directory and not in `docs`.

**Comment by mars** [comment]
Thanks for opening this issue @ijsnow ,

Currently, this buildpack is self-standing, not composable with other buildpacks. It only supports building & serving the React app from the root of the repo as a static website. Directory prefixes are not configurable; those `*_ENV` variables you noticed are refs to the [Heroku `bin/compile` args](https://devcenter.heroku.com/articles/buildpack-api#bin-compile).

I'd love to fork-off another version of this buildpack to  support combining with other buildpacks/apps like Rails, Express, or Django (i.e. without the static/Nginx web server.) Essentially, deploy create-react-app from a sub directory without including a runtime server.

Until such a new version is released, you can switch to use the Node buildpack directly to run the `npm build` in a sub directory with a `--prefix` arg.

**Comment by mars** [comment]
Also, create-react-app requires devDependencies to build, so if you're running the build make sure `NODE_ENV=development`

**Comment by ijsnow** [comment]
@mars thanks for getting back to me! I figured this would be the case. I'll see what I can do with using the Nodejs buildpack! Thanks for the info!

**Comment by thien-do** [comment]
Hi @ijsnow have you successfully achieve this?

I read Mars's instruction above but still don't know how to compile and serve a `create-react-app` app from a sub-directory :(

**Comment by mars** [comment]
@dvkndn this buildpack only supports a top-level React app.

Checkout [create-react-app with Node server](https://github.com/mars/heroku-cra-node) which puts the React app in a subdirectory and documents how to.

**Comment by thien-do** [comment]
thank you @mars !

If anyone interesting in this thread, you can also try https://github.com/lstoll/heroku-buildpack-monorepo . It will move your subdirectory to root and after that, you can use this buildpack normally

**Comment by reedx8** [comment]
> thank you @mars !
> 
> If anyone interesting in this thread, you can also try https://github.com/lstoll/heroku-buildpack-monorepo . It will move your subdirectory to root and after that, you can use this buildpack normally

Thanks but the provided instructions dont make sense? EDIT: Nevermind, was able to solve it much easier instead using Netlify
