### ISSUE TITLE
insert additional proxy

### ISSUE THREAD

**Issue by RohovDmytro** [mars/create-react-app-buildpack#26]
It is possible to insert addional node.js proxy that will take the request and either forward to static webserver or do-other-specific-stuff?

I tried to create Procfile
````
web: node ./proxy/server
````

with content like this:
````js
const express = require('express'),
      path = require('path'),
      app = express(),
      request = require('request'),
      PORT = 5000;

// TODO use 5000 port
const redirectToReactApp = (req, res) => {
  console.log("redirecto to reactp app");
  res.send("redirectToReactApp");
};
const redirectToOpenGraph = (req, res) => {
  console.log("redirecto to open graph");
  res.send("redirectToOpenGraph");
};

app.get('*', true ? redirectToOpenGraph : redirectToReactApp);

app.listen(PORT, () => console.log(`server.js is running on port: ${PORT}`));

````

But it did not help me. Any ideas? Thanks in advance.

**Comment by RohovDmytro** [comment]
Okay. I find out that creating my custom Procfile does not work well with this buildpack. 

@mars can you please add some info to docs how can I provide a custom Procfile (where I can start my proxy server) with default behavior of a buildback? That would be great!

**Comment by mars** [comment]
Hi @rogovdm !

This CRA buildpack actually runs the web process with the Static buildpack which offers proxy config through a custom `static.json` config at the root if your repo. See: https://github.com/heroku/heroku-buildpack-static/blob/master/README.md#proxy-backends

Setting a custom Procfile will override the Static buildpack's default web process, the Nginx web server, which is probably not going to work as desired.

If you want a custom Node/Express server in the same dyno/app as the React UI, then you're best bet is either:

* directly use the Node buildpack for your app (not this buildpack) and setup CRA's `npm build` as a postinstall script in package.json
* try out [Next.js on Heroku](https://github.com/mars/heroku-nextjs) (Universal Javascript App server for React) which supports [using a custom Express server](https://github.com/mars/heroku-nextjs-custom-server-express).

**Comment by RohovDmytro** [comment]
Cool, thanks!

I find out that default Procfile is:
````
web: bin/boot
````

Now I'm figuring out how to start to processes smth like
````
web: bin/boot + node proxy.js
````

**Comment by mars** [comment]
@rogovdm I do not recommend trying to run Nginx + Node. Just use the Node buildpack to build and host your static files, running an Express server to serve the static files plus any custom endpoints.

Please consider the options I took the time to explain, as the path your continuing to follow (combined static + Node) is an anti-pattern.

Either:

* configure proxies in `static.json`,
* build a pure Node app, or 
* leverage something like Next.js which solves this React UI + custom server for you.
