### ISSUE TITLE
Can't deploy rails / react (created with create-react-app) to heroku

### ISSUE THREAD

**Issue by jpstokes** [mars/create-react-app-buildpack#28]
I worked on a deployment project this past weekend where I'm deploying a rails / react app. I followed this tutorial: 

https://www.fullstackreact.com/articles/how-to-get-create-react-app-to-work-with-your-rails-api/

The build and deploy process is successful but I'm unable to open the application. The logs say that 60 secs has expired and the system timed out. I did some research and read something about setting the port dynamically but didn't see how to do so.

I've exhausted all my resources at this point. I'm hoping that you can provide me some insight into fixing this problem.

My files:

root/Procfile

```
api: bundle exec puma -t 5:5 -p ${PORT:-3001} -e ${RACK_ENV:-development}
web: npm run build
```

root/package.json

```
{
  "name": "web",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "build": "cd client"
  }
}
```

root/client/package.json

```
{
    "name": "app",
    "version": "0.1.0",
    "private": true,
    "devDependencies": {
        "react-scripts": "^0.8.4"
    },
    "dependencies": {
        "react": "^15.4.1",
        "react-dom": "^15.4.1",
        "react-router": "^3.0.0"
    },
    "scripts": {
        "start": "react-scripts start",
        "build": "react-scripts build",
        "build:client": "(cd client && npm run build)",
        "test": "react-scripts test --env=jsdom",
        "eject": "react-scripts eject"
    },
    "cacheDirectories": [
        "node_modules",
        "client/node_modules"
    ],
    "proxy": "http://api.lvh.me:3001/v1/"
}
```

**Comment by mars** [comment]
Hi @jpstokes,

I see confusion here around how Heroku's process model and how `Procfile` works. Reading the [process model docs](https://devcenter.heroku.com/articles/process-model) should help clarify.

This GitHub repo is for `create-react-app-buildpack`, which supports deploying a CRA-generated app as a standalone static web site on Heroku. It doesn't sound like that's what you're doing.

Here's how you can use this buildpack as a front-end for a Rails API:

1. separate React & Rails into two separate git repos; deploy two separate Heroku apps:
    1. the React UI (created with CRA `create-react-app` CLI)

        ```bash
        heroku create $APP_NAME --buildpack https://github.com/mars/create-react-app-buildpack.git
        ```
    1. the Rails API (created with `rails` CLI)

        ```bash
        heroku create $APP_NAME --buildpack heroku/ruby
        ```
2. enable API calls from the UI; either:
    * setup [CORS for the Rails API](https://github.com/cyu/rack-cors), or
    * configure the CRA app to [proxy to the Rails backend](https://github.com/mars/create-react-app-buildpack#proxy)

By running two separate apps, you'll be able follow an easy, direct path for each programming framework & buildpack.

Combining a javascript UI framework with an API framework of a different language into a single app is an advanced topic which inevitably requires expertise in both worlds.

**Comment by jpstokes** [comment]
Touche...I'm not an expert in either at the moment but the tutorial made a sound like it was possible. However, when deploying to prodution apparently it's takes a little more in depth knowledge. I still think the concept is good. What would help me is that in depth knowledge on how to make it happen on Heroku in a production environment.

**Comment by mars** [comment]
The blog article you linked seems to be about making it work nicely for local dev. It doesn't seem to say anything production deployment. The `Procfile` shown in that article will definitely not work on Heroku 😔 The author is sharing a local dev technique using `Procfile` to run two processes which is super-confusing if you're trying to deploy to Heroku which also [uses `Procfile` in a very specific way](https://devcenter.heroku.com/articles/procfile).

The point he's trying to convey with foreman/Procfile is to run two processes for local development:

1. React in development mode `npm start`
2. Rails in development mode `bundle exec rails s -p 3001`

Simply run each of those in a separate terminal. Don't mess with foreman/Procfile for this purpose.

From a high-level, assuming both the CRA generated app & the Rails app are located at the root of the repo, here's what is required to deploy them together:

1. add the Node buildpack to your app before the Ruby buildpack.
    * see [Using multiple buildpacks](https://devcenter.heroku.com/articles/using-multiple-buildpacks-for-an-app)
1. `package.json` should define a `postinstall` script to run the JS build
    * my goto is `"if [ \"$NODE_ENV\" = production ] ; then npm run build ; fi"`
1. serve the bundled React app in `build/` from your Rails app or embed it in a view template
