### ISSUE TITLE
`browse` is not a heroku command

### ISSUE THREAD

**Issue by trevordmiller** [mars/create-react-app-buildpack#3]
I followed all instructions in the `README`. Everything worked perfectly except for `heroku browse` which threw this error:

![image](https://cloud.githubusercontent.com/assets/5497885/17798561/75ceaed0-658f-11e6-9dc6-3a4353319ef2.png)

I'm able to manually get to the dashboard at https://dashboard.heroku.com/apps/{my-app-id}.

Although this is probably not related to this project, the `README` should probably be updated with the correct command.

p.s. `create-react-app-buildpack` is a fantastic idea. CRA + Heroku = ❤️. Thank you.

**Comment by mars** [comment]
It seems I have a non-standard Heroku CLI plugin that provides `heroku browse` 🙈. Updated to avoid that mis-information.

Thanks for the posi-feedback @trevordmiller 🙏
