### ISSUE TITLE
"https_only": true doesn't seem to work. 

### ISSUE THREAD

**Issue by firaskrichi** [mars/create-react-app-buildpack#31]
The app doesn't redirect to https. any ideas why? 

static.json:

```
{
  "root": "build/",
  "clean_urls": false,
  "https_only": true,
  "routes": {
    "/**": "index.html"
  }
}
```

Thank you 🙏

**Comment by mars** [comment]
I just tested your exact `static.json` in a Heroku app. It works as expected; plain`http://` requests get redirected to `https://`.

Did you commit & deploy the file?

```bash
git add static.json
git commit -m 'update static web server config'
git push heroku master
```

**Comment by firaskrichi** [comment]
Thanks @mars I was trying to setup the express server at the same time so probably something to do with that. You answer to my other question helped a lot. Thanks 🙏
