### ISSUE TITLE
Can I use my own express server (backend) using the buildpack? 

### ISSUE THREAD

**Issue by firaskrichi** [mars/create-react-app-buildpack#32]
I have an express server setup, and I found a way to make all the routes go through the server in development. 

However as soon as I'm in production, using heroku and this buildpack I have to run 2 servers. Express and the buildpacks. 

Is there a way to only use the express server while still using the buildpack? 

Thank you 🙏

**Comment by mars** [comment]
No, this buildpack is only for static site deployment. It does not compose with a Node/Express server.

We do have a [React + custom Express server example](https://github.com/mars/heroku-nextjs-custom-server-express) using [Next.js](https://github.com/zeit/next.js) which serves React UI as a universal web app, providing server-side rendering through a `pages/` "files as routes" architecture.

If Next is not a good fit for your app, then using the Node buildpack directly is your best bet: combine the React app and Express server into a single repo, set a package.json script `"postinstall": "npm run build"`, and then serve the React app `build/` directory as static files from Express.

**Comment by firaskrichi** [comment]
Thanks! "postinstall": "npm run build" worked!

**Comment by mars** [comment]
Yay!

FYI, to avoid that npm script running when you perform `npm install` locally, set it to run only in production:

`"postinstall": "if [ \"$NODE_ENV\" = production ] ; then npm run build ; fi"`

**Comment by firaskrichi** [comment]
Awesome! Thanks @mars 🙏

**Comment by philjoseph** [comment]
Hi @mars - I am in the same situation like @firaskrichi with a Node/Express app serving APIs and a Create-React-App application. Everything works ok locally even in production mode but the postinstall way does not work. I am getting ` sh: 1: react-scripts: not found`

To be more accurate: I am running the following postinstall step, to ensure that all packages of the CRA will be installed. (web_app is the sub dir where the CRA app is located).

```knex migrate:latest  && cd web_app && npm install && npm run build```

Any advice?

**Comment by mars** [comment]
@philjoseph, `react-scripts` is (by default) a devDependency for CRA apps, but Heroku Node buildpack has environment `NODE_ENV=production` which causes `npm install` to skip devDeps.

To install those devDeps too:

```bash
npm install --only=dev && npm install && npm run build
```

**Comment by mars** [comment]
Here's an example repo to help future folks with the **CRA + Node API combo**:

https://github.com/mars/heroku-cra-node

**Comment by philjoseph** [comment]
It is now crystal clear. Thanks @mars for the explanation and for the example repo. Very useful.

**Comment by firaskrichi** [comment]
@mars I pushed 10 days ago and it worked, pushing now and running into the same problem as @philjoseph . Did anything change between then and now? 

I tried your 'npm install --only=dev && npm install && npm run build' but it keeps running in the console as a never ending loop.

**Comment by firaskrichi** [comment]
I just deployed exactly the same app in staging with production env variables and it works with : "npm run build" only... It's just the production one that doesn't seem to deploy.

**Comment by firaskrichi** [comment]
Adding "react-scripts": "0.7.0" to dependencies solved the problem

**Comment by mradzwilla** [comment]
@mars is the reason I'll be able to sleep peacefully tonight

**Comment by huzaifa3115** [comment]
Still Facing the issue, can anyone help?

**Comment by mars** [comment]
Solution comment [on Jan 30, 2017](https://github.com/mars/create-react-app-buildpack/issues/32#issuecomment-276217163):

> Here's an example repo to help future folks with the **CRA + Node API combo**:
> 
> https://github.com/mars/heroku-cra-node
