### ISSUE TITLE
Create 301 redirect to without www

### ISSUE THREAD

**Issue by shafy** [mars/create-react-app-buildpack#34]
I saw that there is the https enforcement which absolutely rocks! Is there a possibility to redirect to non-subdomain, e.g. https://www.mydomain.com -> https://mydomain.com?

**Comment by mars** [comment]
Hello @shafy !

The underlying static site buildpack does support [custom redirects](https://github.com/heroku/heroku-buildpack-static#custom-redirects), but they do not match hostnames, only paths 😖

Perhaps try configuring this at the DNS service level? Many DNS services support adding "URL redirects" for hostnames, funneling requests to a canonical hostname.

You could also switch to using [create-react-app with a custom Node/Express server](https://github.com/mars/heroku-cra-node), and write a request handler to redirect everything to a canonical hostname.

**Comment by shafy** [comment]
Hey @mars thanks for the super quick reply. I am using DNSimple and they don't provide this use case (see https://support.dnsimple.com/articles/redirect-heroku/#redirect-nohttps). Just posting it if other folks also face the same challenge.

The nodejs server would work I guess, but I am already using Rails as a backend and don't want to have two calls for every set of data I want to fetch :-)

Guess I'll just leave it at both versions for now, it doesn't really matter, in the end the only thing it could impact is SEO.

Thanks again for your answer, still awesome work with the buildpack, and I am using it anyways.

**Comment by mars** [comment]
Sounds good @shafy, it's worth noting that the Node server solution would not add extra requests for the canonical hostname. Only the redirects would be "extra" requests, which will be part of the solution no matter the technical implementation.

**Comment by shafy** [comment]
@mars No i meant API requests to my backend, which is based on Rails. But I am just thinking, could I redirect in my Rails backend?

**Comment by mars** [comment]
To clarify, the Node server would have two handlers:

1. **canonical hostname + HTTPS redirector**
2. **static file server** for the React app

Probably sample code would make it clear. I will update when I have a chance.

**Comment by mars** [comment]
I don't think there's a way to cause a frontend redirect from the backend/API.

**Comment by shafy** [comment]
Sure, I get that. But my point is I don't want to have my business logic in Node, so I would have to have two backends. And the Node one I would just use to redirect to canonical hostname?

**Comment by mars** [comment]
Switching from create-react-app-buildpack to Node buildpack w/ an Express server does not imply any change in location of business logic or API calls.

Making that switch simply means using Express to serve the static React app `build/` files, and then you can write custom server-side logic like the canonical hostname redirector.

The frontend-backend architecture does not [need to] change. It's a pure frontend switch from Nginx web server to Node static file server.

**Comment by shafy** [comment]
Ohh. I see, now I get it. Of course. Thanks for explaining and sorry for wasting your time :-) I'll check it out

**Comment by mars** [comment]
I just realized that the heroku-cra-node example explicitly states the combined UI + API use-case. Sorry for the confusion.

That Node server does not have to be used for an API. Use it to implement any custom front-end, server-side behavior.

**Comment by shafy** [comment]
Yes I think that's why I was confused. Now I get the basic use case and I might switch to it if the www-issue starts bothering me. Good to know that there is the alternative buildpack :-)

Just another question: It doesn't currently support server-side rendering or does it?

**Comment by mars** [comment]
create-react-app does not include server-side rendering. You can find solutions for it, though they get into the weeds fast.

I've found [Next.js on Heroku](https://github.com/mars/heroku-nextjs) to be amazing for creating universal React apps. It is prescriptive about routing and linking, but really takes server-side rendering to the next level.

**Comment by shafy** [comment]
Cool, thanks dude! 👍
