### ISSUE TITLE
After changing to new Sass support getting 404 nginx error

### ISSUE THREAD

**Issue by Jony-Y** [mars/create-react-app-buildpack#37]
I changed the package.json according to the Sass support docs, (all css to scss and package.json)
package json looks now like so:
`"scripts": {
    "build-css": "node-sass src/ -o src/",
    "watch-css": "npm run build-css && node-sass src/ -o src/ --watch --recursive",
    "start-js": "react-scripts start",
    "start": "npm-run-all -p watch-css start-js",
    "build": "npm run build-css react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }`

npm-run-all is also installed under devDep.

As far as the code goes, only changed css to sass. locally everything works fine
when I push to heroku, logs seem fine but Im getting the 404 Not Found nginx.
any idea whats wrong here?

**Comment by mars** [comment]
With this buildpack, npm script `build` is run, then the built React app is served as a static web site. The `start` script will never run; it's only for local development work.

If you're seeing a 404 from the static web server, then it sounds like the `build` script is failing somehow, but not causing the deploy to fail (exit code is `0`).

Did you check the build log for errors during the deployment? Please update the issue with the build log (output from `git push heroku master`).

**Comment by mars** [comment]
Looks like the `build` script has a typo (is missing `&&` between commands):


```
npm run build-css react-scripts build
```

…should be…

```
npm run build-css && react-scripts build
```

**Comment by Jony-Y** [comment]
@mars thanks for the quick answer
tried adding your suggestions - build now failed on  npm run  build-css &&  react-scripts build 
then tried doing:
`"scripts": {
    "build-css": "node-sass src/ -o src/",
    "watch-css": "npm run build-css && node-sass src/ -o src/ --watch --recursive",
    "start-js": "react-scripts start",
    "build-js": "react-scripts build",
    "start": "npm-run-all -p watch-css start-js",
    "build": "npm-run-all -p build-css build-js ",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }`

build failed on  npm-run-all -p build-css build-js 

could it be the file changes? refactoring css files to scss? I remember that renaming sometimes causes these crashes doesnt it?

do you have any idea?

**Comment by Jony-Y** [comment]
@mars  Ok, Yes it was the naming!
Had to remove some css files and readd them and build passed.

Thanks for the assistance!
