### ISSUE TITLE
buildpack description for the uninitiated?

### ISSUE THREAD

**Issue by sidot3291** [mars/create-react-app-buildpack#4]
I had some hesitation going through the readme when I reached the `heroku create` step.

In particular, I was confused because it uses a github URL and there were no steps asking me to push my app to github.

Eventually I looked up `-b` and buildpack and realized I should use the command as-is instead of replacing it. 

But, since other first-timers are using create-react-app, it might be helpful to add some further clarification to the readme.

Otherwise didn't run into any challenges!  Thanks!

**Comment by mars** [comment]
Thanks for feedback from a first-timer's perspective 🚀. I just made a few revisions to clarify what the `git init` & `heroku create …` commands do, hopefully without adding to much complexity to the process.
