### ISSUE TITLE
Staging and Production env variables

### ISSUE THREAD

**Issue by fbarbare** [mars/create-react-app-buildpack#41]
Hi,

I'm facing this issue where I have some environment specific variables like my API URL. When in a pipeline, I click the "promote to production" button, I get in production the variables from Staging. I guess because it hasn't rebuilt the files.

Is there a way to make it work nicely instead to always create a new deployment from the master branch?

Thanks,
Florian

**Comment by mars** [comment]
Yes, see the section on [Runtime Environment Variables](https://github.com/mars/create-react-app-buildpack/blob/master/README.md#environment-variables) in the README.
