### ISSUE TITLE
Support `--no-static` flag

### ISSUE THREAD

**Issue by garrettmaring** [mars/create-react-app-buildpack#42]
Support the ability to exclude the static ngnix server buildpack. I have a use case where I'd like to be able to use the node buildpack + the create-react-app-inner-buildpack but manage the server start script through my `Procfile`.

**Comment by mars** [comment]
Hi @garrettmaring ,

As simple as "adding a flag" may sound, I want to avoid making this buildpack more complex purely to support deployment customization. Its architecture already supports easy recomposition by way of the `.buildpacks` file.

You're welcome to fork, delete the `buildpack-static` line from `.buildpacks` file, and then declare your own `Procfile` in your app.

**Comment by geraldarthurdavis** [comment]
Did exactly that! Just thought I'd post it here to see if you, or anyone in the community, would be interested in having that sort of functionality built into the buildpack.
