### ISSUE TITLE
Broken link in a description

### ISSUE THREAD

**Issue by vacker** [mars/create-react-app-buildpack#45]
Hey there,

https://github.com/reactjs/react-router/blob/master/docs/guides/Histories.md#browserhistory
link in a [Routing clean URLs](https://github.com/mars/create-react-app-buildpack#routing-clean-urls) chapter is broken.
Probably should be https://github.com/ReactTraining/react-router/blob/v3/docs/guides/Histories.md#browserhistory

Great buildpack, btw!

**Comment by mars** [comment]
Thanks @vacker
