### ISSUE TITLE
Undefined REACT_APP custom environment variables

### ISSUE THREAD

**Issue by hsiehdog** [mars/create-react-app-buildpack#5]
Thanks for creating this buildpack, extremely useful and much appreciated!

With the release of react-scripts 0.2.3 it seems like we should have access to environment variables that start with REACT_APP.  I confirmed locally that this is the case, but when I deploy to heroku and use config:set to define say REACT_APP_EXAMPLE_VARIABLE, process.env.REACT_APP_EXAMPLE_VARIABLE is undefined.

I'm not sure if this is an issue with the buildpack or create-react-app, but just wanted to bring it up in case anyone has some insight into this.

https://github.com/facebookincubator/create-react-app/blob/ef94b0561d5afb9b50b905fa5cd3f94e965c69c0/template/README.md#adding-custom-environment-variables

**Comment by mars** [comment]
Interesting new feature!

I believe we can import all `REACT_APP_*` environment variables during the buildpack's compile phase, so that they are in scope when `npm run build` is executed.

I'll try this out soon and update this issue with results.

**Comment by mars** [comment]
Please try the [revision to support env vars](https://github.com/mars/create-react-app-buildpack/pull/6) by setting your app's buildpack to:

```
heroku buildpacks:set https://github.com/mars/create-react-app-buildpack.git#react-app-env-vars
```

Also, note the re-deploy caveat in the [updated docs](https://github.com/mars/create-react-app-buildpack/tree/react-app-env-vars#environment-variables).

Let me know how it goes!

**Comment by mars** [comment]
Nevermind about the trial, it's merged into the buildpack master. Just redeploy to use the new functionality.

**Comment by hsiehdog** [comment]
Works like a charm!  Thanks so much for the quick response!
