### ISSUE TITLE
Is an `app.json` required?

### ISSUE THREAD

**Issue by HiroAgustin** [mars/create-react-app-buildpack#50]
This might be a dumb question given the error message I got from heroku:

> Couldn't create this review app • An app.json is required on branch *NAME*

Note that I am using the pipelines.

Thanks for the great repo!

**Comment by mars** [comment]
Yes, to use with Review Apps, you'll need to add an `app.json`:

https://devcenter.heroku.com/articles/github-integration-review-apps#app-json

**Comment by HiroAgustin** [comment]
Awesome! Thanks for the quick response!
