### ISSUE TITLE
I have problem TypeError: Cannot read property 'request' of undefined

### ISSUE THREAD

**Issue by Peakdrum** [mars/create-react-app-buildpack#51]
I was trying to push my code to heroku and this error happen . 

ExternalModuleFactoryPlugin.js:37 handleExternals
[build_56fd8eac2fb60590722f9b5429d2a529]/[webpack]/lib/ExternalModuleFactory Plugin.js:37:33

ExternalModuleFactoryPlugin.js:46 next
[build_56fd8eac2fb60590722f9b5429d2a529]/[webpack]/lib/ExternalModuleFactory Plugin.js:46:8

ExternalModuleFactoryPlugin.js:59 handleExternals
[build_56fd8eac2fb60590722f9b5429d2a529]/[webpack]/lib/ExternalModuleFactory Plugin.js:59:7

ExternalModuleFactoryPlugin.js:79 ExternalModuleFactoryPlugin.
[build_56fd8eac2fb60590722f9b5429d2a529]/[webpack]/lib/ExternalModuleFactory Plugin.js:79:5

NormalModuleFactory.js:246 applyPluginsAsyncWaterfall
[build_56fd8eac2fb60590722f9b5429d2a529]/[react-scripts]/[webpack]/lib/Norma lModuleFactory.js:246:4

Tapable.js:204 
[build_56fd8eac2fb60590722f9b5429d2a529]/[react-scripts]/[tapable]/lib/Tapab le.js:204:11

IgnorePlugin.js:56 IgnorePlugin.checkIgnore
[build_56fd8eac2fb60590722f9b5429d2a529]/[react-scripts]/[webpack]/lib/Ignor ePlugin.js:56:10

Tapable.js:208 NormalModuleFactory.applyPluginsAsyncWaterfall
[build_56fd8eac2fb60590722f9b5429d2a529]/[react-scripts]/[tapable]/lib/Tapab le.js:208:13

NormalModuleFactory.js:230 NormalModuleFactory.create
[build_56fd8eac2fb60590722f9b5429d2a529]/[react-scripts]/[webpack]/lib/Norma lModuleFactory.js:230:8

Compilation.js:382 Compilation._addModuleChain
[build_56fd8eac2fb60590722f9b5429d2a529]/[react-scripts]/[webpack]/lib/Compi lation.js:382:17

Compilation.js:464 Compilation.addEntry
[build_56fd8eac2fb60590722f9b5429d2a529]/[react-scripts]/[webpack]/lib/Compi lation.js:464:8

SingleEntryPlugin.js:22 SingleEntryPlugin.
[build_56fd8eac2fb60590722f9b5429d2a529]/[webpack]/lib/SingleEntryPlugin.js: 22:15

Tapable.js:229 Compiler.applyPluginsParallel
[build_56fd8eac2fb60590722f9b5429d2a529]/[react-scripts]/[tapable]/lib/Tapab le.js:229:14

Compiler.js:488 
[build_56fd8eac2fb60590722f9b5429d2a529]/[react-scripts]/[webpack]/lib/Compi ler.js:488:8

Tapable.js:131 Compiler.applyPluginsAsyncSeries
[build_56fd8eac2fb60590722f9b5429d2a529]/[react-scripts]/[tapable]/lib/Tapab le.js:131:46

Compiler.js:481 Compiler.compile
[build_56fd8eac2fb60590722f9b5429d2a529]/[react-scripts]/[webpack]/lib/Compi ler.js:481:7
npm ERR! Linux 3.13.0-112-generic
npm ERR! argv "/tmp/build_56fd8eac2fb60590722f9b5429d2a529/.heroku/node/bin/node" "/tmp/build_56fd8eac2fb60590722f9b5429d2a529/.heroku/node/bin/npm" "run" "build"
npm ERR! node v6.11.0
npm ERR! npm v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! btfWeb2@0.1.0 build: react-scripts build
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the btfWeb2@0.1.0 build script 'react-scripts build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the btfWeb2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! react-scripts build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR! npm bugs btfWeb2
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! npm owner ls btfWeb2
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR! /tmp/build_56fd8eac2fb60590722f9b5429d2a529/npm-debug.log
! Push rejected, failed to compile React.js (create-react-app) multi app.
! Push failed

Can you please help ?

**Comment by srt32** [comment]
Looking at the error

>  Make sure you have the latest version of node.js and npm installed.

What versions of `node` and `npm` are you using?

**Comment by mars** [comment]
I don't see an actual error output here, just the `Exit status 1`. Hard to say what's going wrong.

Does this React app build locally? Try with `npm run build`. (Make sure to `rm -r build/` after testing it.)

Would you paste the complete build log?

**Comment by 0010abhi** [comment]
Same problem occured for me also.

here is the log:
>npm install

> node-sass@4.5.3 install D:\angularcli\groom-your-vocab\node_modules\node-sass
> node scripts/install.js

Cached binary found at C:\Users\Abhis\AppData\Roaming\npm-cache\node-sass\4.5.3\win32-ia32-48_binding.node

> node-sass@4.5.3 postinstall D:\angularcli\groom-your-vocab\node_modules\node-sass
> node scripts/build.js

Binary found at D:\angularcli\groom-your-vocab\node_modules\node-sass\vendor\win32-ia32-48\binding.node
Testing binary
Binary is fine

> app-app@0.0.0 postinstall D:\angularcli\groom-your-vocab
> ng build

Hash: fad5584f80131aa1f4b6
Time: 9535ms
chunk    {0} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 184 kB {4} [initial] [rendered]
chunk    {1} main.bundle.js, main.bundle.js.map (main) 51.5 kB {3} [initial] [rendered]
chunk    {2} styles.bundle.js, styles.bundle.js.map (styles) 12 kB {4} [initial] [rendered]
chunk    {3} vendor.bundle.js, vendor.bundle.js.map (vendor) 2.39 MB [initial] [rendered]
chunk    {4} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]

ERROR in   TypeError: Cannot read property 'request' of undefined

  - ExternalModuleFactoryPlugin.js:37 handleExternals
    [groom-your-vocab]/[webpack]/lib/ExternalModuleFactoryPlugin.js:37:33

  - ExternalModuleFactoryPlugin.js:46 next
    [groom-your-vocab]/[webpack]/lib/ExternalModuleFactoryPlugin.js:46:8

  - ExternalModuleFactoryPlugin.js:59 handleExternals
    [groom-your-vocab]/[webpack]/lib/ExternalModuleFactoryPlugin.js:59:7

  - ExternalModuleFactoryPlugin.js:79 ExternalModuleFactoryPlugin.<anonymous>
    [groom-your-vocab]/[webpack]/lib/ExternalModuleFactoryPlugin.js:79:5

  - NormalModuleFactory.js:246 applyPluginsAsyncWaterfall
    [groom-your-vocab]/[cli]/[webpack]/lib/NormalModuleFactory.js:246:4

  - Tapable.js:260 NormalModuleFactory.applyPluginsAsyncWaterfall
    [groom-your-vocab]/[tapable]/lib/Tapable.js:260:70

  - NormalModuleFactory.js:230 NormalModuleFactory.create
    [groom-your-vocab]/[cli]/[webpack]/lib/NormalModuleFactory.js:230:8

  - Compilation.js:378 Compilation._addModuleChain
    [groom-your-vocab]/[cli]/[webpack]/lib/Compilation.js:378:17

  - Compilation.js:460 Compilation.addEntry
    [groom-your-vocab]/[cli]/[webpack]/lib/Compilation.js:460:8

  - SingleEntryPlugin.js:22 SingleEntryPlugin.<anonymous>
    [groom-your-vocab]/[webpack]/lib/SingleEntryPlugin.js:22:15

  - Tapable.js:293 Compiler.applyPluginsParallel
    [groom-your-vocab]/[tapable]/lib/Tapable.js:293:14

  - Compiler.js:483
    [groom-your-vocab]/[cli]/[webpack]/lib/Compiler.js:483:8

  - Tapable.js:195 Compiler.applyPluginsAsyncSeries
    [groom-your-vocab]/[tapable]/lib/Tapable.js:195:46

  - Compiler.js:476 Compiler.compile
    [groom-your-vocab]/[cli]/[webpack]/lib/Compiler.js:476:7

  - Compiler.js:277 Compiler.runAsChild
    [groom-your-vocab]/[cli]/[webpack]/lib/Compiler.js:277:7

  - compiler.js:70
    [groom-your-vocab]/[html-webpack-plugin]/lib/compiler.js:70:19


npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! app-app@0.0.0 postinstall: `ng build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the app-app@0.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Abhis\AppData\Roaming\npm-cache\_logs\2017-09-04T16_09_54_024Z-debug.log

**Comment by mars** [comment]
Hello @0010abhi 

It looks like your error is because something is invoking `request` on an undefined object. Those kinds of errors frequently occur because dependencies are missing or misidentified. This can be a result of dirty `node_modules/` directory (try `rm -rf node_modules && npm install`) or because of mistakes in capitalization of module names or file paths.

Also, it looks like your app is Angular. This is the issues forum for a React deployment tool, the [create-react-app-buildpack](https://github.com/mars/create-react-app-buildpack) for Heroku. Are you using this buildpack?
