### ISSUE TITLE
index.html not updated on deployment

### ISSUE THREAD

**Issue by Kim-Andersen** [mars/create-react-app-buildpack#52]
Hi,
First of all, thanks for creating this build pack. I much appreciate the super easy setup and deployment of a create-react-app on Heroku using this.

That said, I'm experiencing a deployment issue where it seems index.html is not updated, and I suspect nginx cache has something to do with this, in a joined effort with the service worker.

Do you have any suggestion on how to tackle this issue?

Thanks in advance.

**Comment by Kim-Andersen** [comment]
I solved it by configuring a cache header in static.json:
`
"headers": {
    "/**": {
      "Cache-Control": "no-store, no-cache"
    }
  }
`

index.html is still served from the service worker on subsequent requests, which is the desired behavior.

Maybe you want to add this cache header as a default in static.json?

**Comment by bsiddiqui** [comment]
Don't we only need to add cache-control to index.html?

**Comment by mars** [comment]
Yes @bsiddiqui, `cache-control: no-cache` should only be applied to `index.html`. By eliminating cache for all files, performance of the React app will suffer. Create React App uniquely hashes each bundle name so that the static assets can be aggressively cached.
