### ISSUE TITLE
Could not find a required file.

### ISSUE THREAD

**Issue by saikota** [mars/create-react-app-buildpack#53]
Hi,

i have created a react app using create-react-app and trying to push to heroku. 

i am seeing the below error message when i try to push using
git push heroku master.

Build succeeded!
remote: =====> Downloading Buildpack: https://github.com/mars/create-react-app-inner-buildpack.git
remote: =====> Detected Framework: React.js (create-react-app)
remote:        Writing `static.json` to support create-react-app
remote:        Enabling runtime environment variables
remote:
remote: > myappthree@0.1.0 build /tmp/build_12bfae77e82681d2d6968585377319b8
remote: > react-scripts build
remote:
remote: Could not find a required file.
remote:   Name: index.js
remote:   Searched in: /tmp/build_12bfae77e82681d2d6968585377319b8/src
remote:
remote: npm ERR! Linux 3.13.0-112-generic
remote: npm ERR! argv "/tmp/build_12bfae77e82681d2d6968585377319b8/.heroku/node/bin/node" "/tmp/build_12bfae77e82681d2d6968585377319b8/.heroku/node/bin/npm" "run" "build"
remote: npm ERR! node v6.11.0
remote: npm ERR! npm  v3.10.10
remote: npm ERR! code ELIFECYCLE
remote: npm ERR! myappthree@0.1.0 build: `react-scripts build`

can you please help

**Comment by mars** [comment]
The error log indicates that `./src/index.js` is missing. Is it committed to git? What does `git status` return?

**Comment by saikota** [comment]
yes, index.js is present in src folder. Also, i am able to run my app locally with out any issues.

This error is coming up only when i am trying to deploy to heroku.

**Comment by mars** [comment]
The error during Heroku build says that `index.js` is not present in `src/` directory.

I ask again, what does `git status` return when run in your local?

I can think of one more possibility:

Are you developing on a branch instead of `master`?  Then deploy command is

```bash
git push heroku my-branch-name:master
```

…otherwise you're deploying master to master.

**Comment by saikota** [comment]
Hi Mars,

Git Status returns this message:
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean

**Comment by saikota** [comment]
Finally, was able to deploy code from a different machine. 

> Upgraded Heroku Toolbelt Version. 

> added procfile with following command:
web: npm start

not sure exactly what changed.

**Comment by mars** [comment]
If you're defining a Procfile with `web: npm start` then your app has customizations beyond the scope of this buildpack. I doubt that's what you intended, but if it's working then that's a great first step. Glad you figured it out!

**Comment by saikota** [comment]
Thanks for all your replies @mars  !!
