### ISSUE TITLE
Heroku CI Support

### ISSUE THREAD

**Issue by HiroAgustin** [mars/create-react-app-buildpack#56]
After turning on Heroku CI, when trying to run tests the following error message shows up:

#### TEST SETUP ERRORED
```
-----> Reading manifest...
-----> Fetching https://github.com/mars/create-react-app-buildpack.git buildpack...
       buildpack downloaded
 !     Unable to detect any runnable tests.
 !     For more information on how to resolve the issue, please see:
 !     https://devcenter.heroku.com/articles/heroku-ci-prerelease
```

Notice I'm using Heroku Pipelines for automated deployments and I have ejected my create-react-app project.

Its worth mentioning that running `npm test` locally does run the test suite correctly.

**Comment by mars** [comment]
Thanks for opening this issue. I've been meaning to add [Testpack API](https://devcenter.heroku.com/articles/testpack-api) support to this buildpack.

I'll address this soon and follow up here.

**Comment by HiroAgustin** [comment]
Thank you for the quick response. Please let me know if there's anything I can do to help.
Thanks for the **GREAT** repo btw.

**Comment by mars** [comment]
🏁 Done. Please, follow-up here if you experience any issues.

**Comment by mars** [comment]
📚 Docs added to [README](https://github.com/mars/create-react-app-buildpack#user-content-testing)

**Comment by HiroAgustin** [comment]
Forgot to thank you for the CI Support, working like a charm. Really appreciate it, thanks!
