### ISSUE TITLE
Build in heroku shows my webpack folder with src

### ISSUE THREAD

**Issue by Jony-Y** [mars/create-react-app-buildpack#61]
Hi,
I noticed that while everything is working. the buildpack (Im assuming since it builds the entire project in heroku) also shows my webpack folder allowing the access to the unuglified js filed

my static.json is:
`{
  "root": "build/",
  "clean_urls": false,
  "routes": {
    "/**": "index.html"
  },
  "https_only":true,
  "headers": {
    "/**": {
      "Strict-Transport-Security": "max-age=7776000"
    }
  }
}`
and in my production sources I can see the webpack:
![image](https://user-images.githubusercontent.com/10330531/28358155-6886b6a2-6c76-11e7-81f9-cb9995699cd5.png)

via the . folder you can access the src.

how do I prevent that?

**Comment by lavrton** [comment]
@Jony-Y try this: https://github.com/mars/create-react-app-buildpack/issues/59#issuecomment-316354389

**Comment by Jony-Y** [comment]
@lavrton  thanks! worked perfectly
