### ISSUE TITLE
Execute node in custom .profile.d script

### ISSUE THREAD

**Issue by pepesenaris** [mars/create-react-app-buildpack#64]
I'm trying to execute an inline node script inside a .profile.d script.
Something like 
`VAR1=$(curl -s https://api.github.com/repos/somerepohere/pulls?access_token=some_token_here | node -pe "let pr = JSON.parse(require('fs').readFileSync('/dev/stdin').toString())")`

The issue is that node is not found, so I'm not sure if that's even possible or if I need to execute node from a specific path set by the buildpack

**Comment by mars** [comment]
Out of curiosity, did you figure out the problem?

**Comment by pepesenaris** [comment]
Yes, I was in a rush yesterday trying to "fix the world", sorry for closing the issue just like that.
I end up using a one-time dyno (which I was not aware of when opening the issue) to login in the review app and once there I got the actual path for node.

great work with the buildpack!!!

**Comment by mars** [comment]
Nice! Glad to hear it @pepesenaris
