### ISSUE TITLE
Express Server + Static React - 404 Not Found Nginx Live Error

### ISSUE THREAD

**Issue by exapsy** [mars/create-react-app-buildpack#67]
My application has a **404 Not Found Nginx** error. I can't quite understand why so.

What I'm trying to do is to upload a **Express Server** + **Static React Page** as a whole app. My deployment/git-push is alright without errors. 
I tried many methods although listing to you may be probably just a pedantic thing to do. So feel free to not read it if that's not useful to you.

- Tried installing **react-app-buildpack** which combines 3 other buildpacks. I tried with and without the heroku/nodejs. Of course having heroku/nodejs made the things quite buggy and my git push heroku master was failing.
- Tried having a `/static.json` on the root, but changed the `root` to `/client/build` instead of `/build`. Still nothing.
- Tried running without **buildpacks**. Nah.
- Tried setting the `homepage` **property** of `/client/package.json` to `https://herokuAppDomain.herokuapp.com/` ... still nothing.
- Other things not worth to mention ...

Absolutely nothing worked and I find no clear log to specifically say what's wrong.

## My App Tree [**Non-Pedantic** / **Simplified**]:
```
. server
├── client
│   ├── etc
│   ├── package.json
│   ├── package-lock.json
│   ├── public
│   │   ├── favicon.ico
│   │   ├── index.html
│   │   └── manifest.json
│   ├── README.md
│   └── src
│       ├── index.js
│       └── registerServiceWorker.js
├── index.js
├── package.json
```
## Package.json - Scripts:
```
"scripts": {
    "start": "node index.js",
    "server": "nodemon index.js",
    "client": "npm run start --prefix client",
    "dev": "concurrently \"npm run server\" \"npm run client\"",
    "build": "npm run build --prefix client",
    "heroku-postbuild": "NPM_CONFIG_PRODUCTION=false cd client/ && npm install && npm run build"
  },
```

**Comment by mars** [comment]
Follow the guidance from the [Purpose section of README](https://github.com/mars/create-react-app-buildpack#user-content-purpose):

Switch to [create-react-app + Node.js server on Heroku](https://github.com/mars/heroku-cra-node)

**Comment by exapsy** [comment]
@mars I have to ask ... are the Guidelines strict?
I mean, do I have to do exactly these :

- Make a `react-ui` folder, and name it exactly as it is
- Make a `server` folder, and name it exactly as it is

Do I have to follow exactly these [directory + name] rules?

**Comment by mars** [comment]
No, you don't have to follow that naming. Just make sure to update those names everywhere they're used (in `package.json` & `server/index.js`), or else things will break. Of course, sometimes it's better to break it yourself to understand it!

**Comment by heshamelmasry77** [comment]
@mars Hey man i still get the same error 404

**Comment by exapsy** [comment]
@heshamelmasry77 What did you and did not try, what are your settings, did you follow the guideline in the link etc. Give us some information about your problem.

**Comment by khalilhijazi** [comment]
@mars @Eksapsy I'm getting an error still even after following the guidelines. I'm getting the same error @heshamelmasry77 is getting.
