### ISSUE TITLE
code in sub folder

### ISSUE THREAD

**Issue by gperdomor** [mars/create-react-app-buildpack#72]
Hi... I have a repo but the `create-react-app` code is inside a sub folder, not in the root of git repository, can I use this buildpack with some parameter to set the root folder? this is the project https://gitlab.com/gperdomor/demo-reactjs/

**Comment by mars** [comment]
No, this buildpack only supports a top-level React app. I’ve heard this request a few times, but my feeling is that this would unduly complicate the buildpack.

Heroku works on a repo-per-app basis, so this matches behavior. The monorepo concept has benefits though! There’s a [buildpack for that](https://github.com/lstoll/heroku-buildpack-monorepo). Looks experimental but maybe could help you.
