### ISSUE TITLE
Deployment ignores Node version specified in package.json

### ISSUE THREAD

**Issue by TravelingTechGuy** [mars/create-react-app-buildpack#73]
I have the following specified in my package.json:

```
"engines": {
    "node": "8.x"
  },
```

However, when I push my app to Heroku (after it was created with `create-react-app`, using the `create-react-app-buildpack`), I get:

```
remote: -----> Installing binaries
remote:        engines.node (package.json):  8.x
remote:        engines.npm (package.json):   unspecified (use default)
remote:
remote:        Resolving node version 8.x...
remote:        Downloading and installing node 8.7.0...
remote:        Detected package-lock.json: defaulting npm to version 5.x.x
remote:        Bootstrapping npm 5.x.x (replacing 5.4.2)...
remote:        npm 5.5.1 installed
```

Why can't I get Node 8.x? What am I missing?

**Comment by mars** [comment]
According to the log you posted, the build is using Node 8:

> `Downloading and installing node 8.7.0..`

What makes you suspect the Node version is wrong?

**Comment by TravelingTechGuy** [comment]
The last two lines the me, talking about 5.x.x - didn't realize it was npm
and not node 😁.

Please close the issue.

Regards,
Guy Vider

(sent from a mobile device)
