### ISSUE TITLE
Remove `https_only` from remote `static.json` file

### ISSUE THREAD

**Issue by TravelingTechGuy** [mars/create-react-app-buildpack#74]
I followed the instructions and added `"https_only": true` to a `static.json` file. However, since I use a custom domain to refer to Heroku, and since this domain does not have an SSL certificate, I kept getting the Chrome error page.

I tried deleting the local `static.json` file and re-pushing to Heroku, but to no avail - the setting seems to be stuck somewhere. So if I try to go to "mydomain.com" it gets referred to "https://mydomain.com" and shows an error page.

Ho can I delete/reset the `https_only` flag on the remote? Or will I need to destroy and recreate the app?

**Comment by mars** [comment]
Did you delete it from the repo and redeploy?

```bash
git rm static.json
git commit -m 'Remove custom static site config'
git push heroku master
```

**Comment by TravelingTechGuy** [comment]
Tried that. Still trying to redirect to https. Wondering if I should create
an explicit `static.json` without that instruction, and push it.

Regards,
Guy Vider

(sent from a mobile device)

**Comment by mars** [comment]
The HTTPS redirect is a `301` Permanent Redirect status code, so you're probably dealing with a [browser caching issue](https://stackoverflow.com/questions/9130422/how-long-do-browsers-cache-http-301s#21396547), now.

**Comment by TravelingTechGuy** [comment]
Makes sense. I'll clear cache. You can close the issue.

Thanks for all your time and hard work!

Regards,
Guy Vider

(sent from a mobile device)

**Comment by mars** [comment]
BTW, Heroku does support [free, automated certificate management for custom domains](https://devcenter.heroku.com/articles/automated-certificate-management) on Hobby dynos and up.

**Comment by mars** [comment]
Clearing the cache will not fix a stuck 301 redirect. Please read the linked article about how to undo such a mistake.
