### ISSUE TITLE
Is it possible not to have react app in root of the Git repo ?

### ISSUE THREAD

**Issue by kavink** [mars/create-react-app-buildpack#77]
I would like the UI and server side reside in 2 separate folders in root of the git repo. Wondering if its possible to let build pack to "chdir" before doing anything ?

**Comment by mars** [comment]
No, this buildpack is for deploying only the frontend app, and it expects the React app `package.json` to be at the root. If you're interested in running a Node backend that also serves the React app, then checkout [create-react-app with a Node server on Heroku](https://github.com/mars/heroku-cra-node).
