### ISSUE TITLE
SASS/CSS not loading (ejected)

### ISSUE THREAD

**Issue by kejtizuki** [mars/create-react-app-buildpack#79]
I'm new to heroku and I'm trying to  build my app. I've used create react app and sass loaders. When I deploy to Heroku I get 'success' but after Heroku open I'm getting an error. In Heroku logs I can see that there is a problem with sass-loader 'Cannot find sass-loader'. Do you have any idea what might be an issue here? 
I included sass in webpack config and package-json.

**Comment by mars** [comment]
Welcome @kejtizuki 😃

Have you verified that this works locally? Depending on your local node/npm versions and how you installed the packages, it's possible that this would work locally but not when deployed. The best way I can recommend to diagnose this is to reset your local Node modules:

```bash
rm -rf node_modules
npm install
npm start
```

How are you updating the Webpack config? Did you eject the create-react-app project?

Finally, you mention that `sass` is configured, but the error seems to be from `sass-loader`. Did you include the Webpack sass-loader in your dependencies?

If you post a link to your GitHub repo, we may be able to help diagnose further.

**Comment by kejtizuki** [comment]
Yes I used npm start to build an app and everything worked for me. I also tried reseting node_modules but it didn't help me. I also included sass-loader. I would be very grateful if you could check: https://github.com/kejtizuki/socialgraphs
I'm not very advanced in using all these technologies so I might have made some basic error as well... 
Thanks so much!

**Comment by mars** [comment]
Hi @kejtizuki, I took a look at you repo source, and it seems eject was used to enable features (like SASS) beyond what create-react-app supports. This is advanced territory that I (an advanced developer) avoid if at all possible. I suggest dropping SASS and returning to the CSS strategies supported by create-react-app.

Also, I did find that `npm start` for development does render the app with styles, but running `npm run build` for production results in an app without styles. So, this issue can be reproduced locally; it's not specific to Heroku deployment.

Good luck with your app… I'm sorry I do not have the time to freely support these customization issues.

**Comment by kejtizuki** [comment]
Ok, I'll try to do what you wrote. Thank you!

**Comment by debelopumento** [comment]
@kejtizuki 
If scss styling is only working in dev environment but not when you build it. It could be that you've only done the configuration in your dev webpack but not in production webpack. Adding the following to production webpack under module might solve this:
`{
            test: /\.scss$/,
            loaders: ['style-loader', 'css-loader', 'sass-loader'],
          },`

**Comment by RichardPK** [comment]
@debelopumento 
> `{ test: /\.scss$/, loaders: ['style-loader', 'css-loader', 'sass-loader'], },`

That's the ticket. Thank you!
