### ISSUE TITLE
Heroku - react -truffle  Error: nginx: [emerg] invalid number of arguments in "root" directive in ./config/nginx.conf:40

### ISSUE THREAD

**Issue by pratgen** [mars/create-react-app-buildpack#81]
Hi,
I am facing issue with deployment on heruku.
I did not modify a single line of code, using Linux ubuntu and node js 8.9.
Here are my commands
mkdir test
cd test
truffle unbox react  (this is as per guidence at reactbox https://github.com/mars/create-react-app-buildpack)
git init
heroku create pratikmrpv --buildpack https://github.com/mars/create-react-app-buildpack.git

git add .
git commit -m 'first commit'
git push heroku master
heroku open
The application does not run shows message 
" Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. "
Here is complete log.
https://www.dropbox.com/s/x1mm0o2nc3xsbnj/heroku%20error%20log.txt?dl=0

before runing those commands I have added below code in static.json
{
  "root": "build_webpack /"
}
as suggested by the guide.
https://medium.com/taipei-ethereum-meetup/ethereum-dapp-tutorial-push-button-cae3810086a4 
You can translate it to English via google translate.

thank you

**Comment by mars** [comment]
Hi @pratgen,

That Nginx error is caused by a bad property value in **static.json** for `"root"`. Probably the value you set for `"root"` does not exist. I'm guessing that the space in `build_webpack /` is accidental. Instead, try:

```json
{
  "root": "build_webpack/"
}
```

**Comment by pratgen** [comment]
Hi Mars,
You are my life savior.
Thank you so much for identifying the silly mistake.
This error cost me two days of delay.
Once again Thank you so much.

**Comment by mars** [comment]
Great to hear. Cheers 🍻
