### ISSUE TITLE
rewrite all to index.html

### ISSUE THREAD

**Issue by dht** [mars/create-react-app-buildpack#86]
In our project we use react-router-dom and we defined a route:
> /example.com/referral

It will not work when navigating directly to it as not all routes are redirected to:
> /build/index.html

How can I rewrite all routes to /build/index.html?

**Comment by mars** [comment]
The [routes](https://github.com/mars/create-react-app-buildpack/blob/master/README.md#user-content-routing-clean-urls) directive of `static.json` is designed to solve this problem.

**Comment by dht** [comment]
Do I just put the static.json in the root folder?

**Comment by mars** [comment]
@dht yes
