### ISSUE TITLE
Issue with build

### ISSUE THREAD

**Issue by justinkchen** [mars/create-react-app-buildpack#87]
When I try to run this buildpack on an app that includes the BigNumber.js package, everything seems to work fine except that the BigNumber object is not recognized throughout the code.  It seems like the building of the file causes some error or maybe its the static.json that I'm using?...I know it may be a little vague, but do you have any idea what could have caused one of the packages to act weird?

**Comment by mars** [comment]
Hi @justinkchen, I'd love to help but need a few more details. Please reply with:

* the current buildpack config from `heroku buildpacks`
* the build logs output from `git push heroku master`
* how is BigNumber.js installed/required in your app?

**Comment by justinkchen** [comment]
It is just installed via package.json, but also it is required by an underlying `0x.js` package.  i found out that its an issue with serving it statically. when I do a `serve -s build` locally, it finally exhibits the same behavior.  Any ideas on some pitfalls about static serving? I already made it so that it served from /static/* first inside of the `build/` folder

**Comment by mars** [comment]
Even if it’s still broken, reproducing the problem locally is a big step forward 👍

To diagnose runtime problems with the JS/React app, try using the Network and also Console in the browser’s dev tools to watch for failing requests and javascript errors.

**Comment by mars** [comment]
BTW, not sure what you mean here,

>  I already made it so that it served from /static/* first inside of the build/ folder

I suspect this refers to changing the **static.json** `root`. That property must remain set to `build/`. Changing to something else for create-react-app will result in a broken runtime.

**Comment by justinkchen** [comment]
So I think I was finally able to figure it out by adding "BigNumber" to the "no mangle" list in webpack (After ejecting the react-scripts).  I then also referenced here (https://github.com/ethereum/web3.js/issues/1121) and changed the `mainFields: ["browser", "main"]`.  Some combination of those two changes fixed it for me.  Thanks for your time!!
