### ISSUE TITLE
CORS warning

### ISSUE THREAD

**Issue by phill999** [mars/create-react-app-buildpack#91]
Hi there,

I am facing issues with CORS settings. I deployed my app and everything works fine in Safari, Chrome, Firefox & Vivaldi on OSX but IE and mobile Safari are aborting my requests.

My app is on heroku and database is on another server I don't have access to.

I tried to set 'mode: no-cors' into my request headers but it didn't help.

I guess there will be something wrong with my proxy setting? Thanks for your help.

This is my static.json file:

{
  "root": "build/",
  "clean_urls": false,
  "routes": {
    "/**": "index.html"
  },
 "https_only": true,
  "proxies": {
    "/build/": {
      "origin": "https://myapp.herokuapp.com"
    }
  },
  "headers": {
    "/**": {
      "Strict-Transport-Security": "max-age=7776000"
    }
  }
}

**Comment by mars** [comment]
CORS is specified by response headers from the server and enforced by the browser when making XHR requests. There is no way to disable CORS in the browser for a server/origin that specifies it.

If XHR requests from the React app are in fact using a proxy endpoint within the same origin (i.e. same app, base URL), then CORS will ~not be the issue~ only be the issue if the proxied service sends conflicting CORS headers.

The built in proxy is already pretty [well documented](https://github.com/mars/create-react-app-buildpack/blob/master/README.md#user-content-proxy), so I’m not sure how much more useful info I can provide there.

If the proxy works for some browsers and not others, then the problem is probably not server-side config. I would look closely at how the XHR requests are being made in the javascript code.

How are these XHR requests being made? Are they using full HTTPS URL?

When you see the connection is aborted, is that in the browser or server-side? (Where can you see the connection attempted?)

**Comment by phill999** [comment]
Hi mars, thank you for your response.

I am trying to follow this idea - basically I am a frontend developer learning React. 
https://m.alphasights.com/using-nginx-on-heroku-to-serve-single-page-apps-and-avoid-cors-5d013b171a45

It was working without proxy - for some browsers. This is the reason, why I am trying to se it up.

This is my request from Redux-Saga:

const loginUrl = `${process.env.REACT_APP_API_URL}/auth/native`;

function loginApi (email, password) {
    
return fetch(loginUrl, {
  method: 'POST',
  headers: {
    'Content-Type': 'application/json',
    'APIKey': 'myApiKey'
  },
     body: JSON.stringify({email, password}),

  }, function (error, response, body,) {
    console.log('Status:', response.statusCode);
    console.log('Headers:', JSON.stringify(response.headers));
    console.log('Response:', body);
  })
  .then(handleReponseErrors)
  .then(response => handleResponse(response))
  .then(json => json)
  .catch((error) => { throw error })
}

And here is a screenshot:
![screenshot](https://user-images.githubusercontent.com/37136648/37105228-e39bf17c-222e-11e8-9ebc-a8529362ea63.png)

![screenshot2](https://user-images.githubusercontent.com/37136648/37107858-b6dc31fe-2235-11e8-86d4-42bd97ab5e38.png)

**Comment by phill999** [comment]
![screen shot 2018-03-06 at 19 05 18](https://user-images.githubusercontent.com/37136648/37105321-2000c61a-222f-11e8-955c-d1b7cda9e426.png)

**Comment by phill999** [comment]
![screen shot 2018-03-02 at 17 29 53](https://user-images.githubusercontent.com/37136648/37105347-324d1440-222f-11e8-8c4d-ee96b8dbefe9.png)

**Comment by phill999** [comment]
URL is defined with https://... I also tried to replace it in my Saga request with full path but it didn't help.

When I try to fill incorrect login and password everything work as expected. My app fires up error message - it means code should be OK. I didn't find any strange code which shouldn't work in other browsers.

I have spent many hours trying to fix this problem already.

Here is similar discussion explaining why some browsers have issues with CORS:

"It is an issue with the browser. JS in the browser will reject requests to servers that do not have the proper headers set. If you're using this with something like React on the client then do not be confused, this is not a React problem, it is simply the browser respecting CORS standard."

https://github.com/axios/axios/issues/191#issuecomment-311069164

The question is, if I understood it correctly =) Thank you for your help.

**Comment by phill999** [comment]
And here is the authorization code:

import {setUser} from './user/actions';

function checkAuthorization(dispatch) {

  const storedToken = localStorage.getItem('token');

  if (storedToken) {

    const token = JSON.parse(storedToken);
    const createdDate = new Date(token.created);
    const created = Math.round(createdDate.getTime() / 1000);
    const ttl = 1209600;
    const expiry = created + ttl;
    if (created > expiry) return false;
    dispatch(setUser(token));
    return true;
  }

  return false;
}

export function checkIndexAuthorization ({ dispatch }) {

  return (nextState, replace, next) => {

    if (checkAuthorization(dispatch)) {
      replace('/events');
      return next();
    }

    replace('/login');
    return next();
  }
}

export function checkEventAuthorization ({ dispatch, getState }) {

  return (nextState, replace, next) => {
    const user = getState().user;

    if (user && user.token) return next();

    if (checkAuthorization(dispatch)) return next();

    replace('/error-page');
    return next();
  }
}

**Comment by phill999** [comment]
The reason why I tried to put /build/ folder into proxy is that I am confused about those headers =) I also tried to put there backend path but with no success.

**Comment by mars** [comment]
What URL is set into `loginUrl`?

```javascript
const loginUrl = `${process.env.REACT_APP_API_URL}/auth/native`;
```

Is it the exact same origin as the React app is served?

What are the headers sent back from that `/auth/native` OPTIONS request? My guess is that the server is sending CORS headers (passing through the proxy) that restrict usage to only its origin.

**Comment by phill999** [comment]
No, ${process.env.REACT_APP_API_URL} is on different server than the React app  - this is the reason I am trying to use proxy - as I understand, according to this article, this is the only one useful solution. Please read this article, this is about heroku-buildpack-static

"Using NGINX on Heroku to Serve Single Page Apps and Avoid CORS"

https://m.alphasights.com/using-nginx-on-heroku-to-serve-single-page-apps-and-avoid-cors-5d013b171a45

and this is his first article describing this problem: 

"Killing CORS Preflight Requests on a React SPA"

https://m.alphasights.com/killing-cors-preflight-requests-on-a-react-spa-1f9b04aa5730

**Comment by phill999** [comment]
![screen shot 2018-03-07 at 21 31 11](https://user-images.githubusercontent.com/37136648/37116739-6dd0c226-224f-11e8-9485-3e32a84b1e4c.png)

**Comment by phill999** [comment]
![screenshot3](https://user-images.githubusercontent.com/37136648/37116964-15881e42-2250-11e8-98a4-01a46884eed7.png)

Origin and Host are two different domain names.

Where is that restriction set - Accept "/" - on Heroku server or on the other one? I would say, because of it is a request header, it means on Heroku? Shouldn't we be able to modify it?

**Comment by mars** [comment]
The whole purpose of the proxy is so you can make fetch/XHR requests **to the same origin** and have them forwarded to a service at a different origin. Otherwise, the browser will not allow such cross-origin requests, the problem you're stuck on.

Example:

* React app is `https://frontend.herokuapp.com` (where the proxy is running)
* Backend API is `https://api.example.com`

The React app's `static.json` should contain:

```json
{
  "proxies": {
    "/api/": {
      "origin": "https://api.example.com"
    }
  }
}
```

…and the React fetch URL to an API resource such as `/auth/native` should be:

```javascript
const loginUrl = "https://frontend.herokuapp.com/api/auth/native";

fetch(loginUrl, …);
```

Since you said:

> Origin and Host are two different domain names.

It seems you're still using `https://api.example.com` as the fetch URL, which completely skips the proxy.

**Comment by phill999** [comment]
Haha, I understand now - stupid me =) I modified loginUrl but in the wrong way. Thank you so much =)

**Comment by mars** [comment]
Yay! Good luck with your app 🙇 😄
