### ISSUE TITLE
Deploy Build version to Heroku, not the development one

### ISSUE THREAD

**Issue by maulberto3** [mars/create-react-app-buildpack#95]
Hi, this may not be an issue. If so, I apologize. However, I want to know how to deploy the build version of a create-react app to Heroku. 

When I do `npm start`, I see Chrome's React Developer Tools (RDT) telling the app is running locally the _development_ version. 
When I do `npm run build`, then `serve -s build`, I see Chrome's RDT telling the app is running locally the _build_ version.
When I do `git push heroku master`, the _development_ version is pushed.

How to push to Heroku the _build_ version, if that's possible?

**Comment by mars** [comment]
Hi @maulberto3 ,

This buildpack implicitly builds & deploys a production bundle:

![screen shot 2018-03-26 at 1 47 39 pm](https://user-images.githubusercontent.com/17164/37932113-89ddc1f6-30fc-11e8-9532-a2acfc728313.png)

I honestly don't know how you could make it deploy the development version.

Are you sure you're using this buildpack for the app? What is output by the following command?

```bash
heroku buildpacks
```

Also, please paste the build log that is output from `git push heroku master`.

**Comment by maulberto3** [comment]
Hi @mars. So `heroku builpacks` (at my root CRA project) gives:
```
=== crc-sen-maps Buildpack URL
heroku/nodejs
```
because I followed this repo's instructions. Note that I already had my app built (and my git with VS Code), so I adjust it accordingly by setting the buildpack with `heroku create $APP_NAME --buildpack https://github.com/mars/create-react-app-buildpack.git` at my command line.

My `npm run build` gives:
```
> crc-sen-maps@0.9.2 build c:\IE\crc-sen-maps
> react-scripts build

Creating an optimized production build...
Compiled with warnings.

./src/components/Filters.js
  Line 3:  'Checkbox' is defined but never used  no-unused-vars

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

File sizes after gzip:

  147.79 KB  build\static\js\main.0769ef47.js

The project was built assuming it is hosted at the server root.
To override this, specify the homepage in your package.json.
For example, add this to build it for GitHub Pages:

  "homepage" : "http://myname.github.io/myapp",

The build folder is ready to be deployed.
You may serve it with a static server:

  serve -s build
```
Then, my `git push heroku master` gives:
```
Counting objects: 6, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (6/6), done.
Writing objects: 100% (6/6), 532 bytes | 177.00 KiB/s, done.
Total 6 (delta 4), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Node.js app detected
remote:
remote: -----> Creating runtime environment
remote:
remote:        NPM_CONFIG_LOGLEVEL=error
remote:        NODE_VERBOSE=false
remote:        NODE_ENV=production
remote:        NODE_MODULES_CACHE=true
remote:
remote: -----> Installing binaries
remote:        engines.node (package.json):  unspecified
remote:        engines.npm (package.json):   unspecified (use default)
remote:
remote:        Resolving node version 8.x...
remote:        Downloading and installing node 8.10.0...
remote:        Using default npm version: 5.6.0
remote:
remote: -----> Restoring cache
remote:        Loading 2 from cacheDirectories (default):
remote:        - node_modules
remote:        - bower_components (not cached - skipping)
remote:
remote: -----> Building dependencies
remote:        Installing node modules (package.json + package-lock)
remote:        added 2 packages and updated 3 packages in 16.638s
remote:
remote: -----> Caching build
remote:        Clearing previous node cache
remote:        Saving 2 cacheDirectories (default):
remote:        - node_modules
remote:        - bower_components (nothing to cache)
remote:
remote: -----> Pruning devDependencies
remote:        Skipping because npm 5.6.0 sometimes fails when running 'npm prune' due to a known issue
remote:        https://github.com/npm/npm/issues/19356
remote:
remote:        You can silence this warning by updating to at least npm 5.7.1 in your package.json
remote:        https://devcenter.heroku.com/articles/nodejs-support#specifying-an-npm-version
remote:
remote: -----> Build succeeded!
remote: -----> Discovering process types
remote:        Procfile declares types     -> (none)
remote:        Default types for buildpack -> web
remote:
remote: -----> Compressing...
remote:        Done: 72.9M
remote: -----> Launching...
remote:        Released v21
remote:        https://crc-sen-maps.herokuapp.com/ deployed to Heroku
remote:
remote: Verifying deploy... done.
To https://git.heroku.com/crc-sen-maps.git
   bb81dbc..09e1789  master -> master
```

Any solution?

**Comment by mars** [comment]
Hi @maulberto3 

Based on your `heroku buildpacks` output & the build log, I see your app is still using **heroku/nodejs** buildpack, not this **mars/create-react-app-buildpack**.

See [the troubleshooting steps](https://github.com/mars/create-react-app-buildpack#user-content-troubleshooting) for how to switch over to this buildpack.

This buildpack will produce the production React build you're seeking 🎯😄

**Comment by maulberto3** [comment]
Awesome, ok, I'll let you know how it goes. Thank you.

**Comment by maulberto3** [comment]
Hi @mars, it worked beautifully. For clarity, may I know why I was having this issue and why this repo works nicely for deploying React build versions to Heroku? Why is this not under the official docs of Heroku? I'd love to know.

**Comment by mars** [comment]
Yay @maulberto3 🤸‍♂️ 

This buildpack is something I created to make production-quality deployment of **create-react-app** as easy as possible. It is not official Heroku product.

Heroku has a whole ecosystem of contributed [buildpacks](https://elements.heroku.com/buildpacks) alongside the officially supported languages (Ruby, Node, PHP, Go, Python, Java, Scala, Closure…) This is just one of those contributed buildpacks.

If you take a look at this buildpack's [architecture](https://github.com/mars/create-react-app-buildpack#user-content-architecture-), you'll see that it's more than just Node.

**Comment by maulberto3** [comment]
Hi @mars Seems Heroku is asking for a **--app flag** as required for setting new buildpacks. I am running the different buildpack command right in my root app, and last time, as you know, it worked. Why is it asking for a -app flag (with a value) now, even in sitting in my root folder?

**Comment by mars** [comment]
The `heroku` command-line will infer which app it belongs to based on the git remote.

See the currently configured remotes:

```bash
git remote -v
```

If a Heroku app is setup, you'll see `heroku` remote in that listing. That is also how `git push heroku master` knows where to push your code 😉 

If the `heroku` remote is missing or incorrect, you can set it with:

```bash
heroku git:remote $APP_NAME
```

✏️ *Replace `$APP_NAME` with the Heroku app's name.*

Once the remote is set correctly, you should be able to run `heroku` commands without specifying `--app` each time.

**Comment by maulberto3** [comment]
Thanks a million @mars
